- name: Creates directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/monitoring/prometheus"
    state: directory
    mode: 0755

- name: Creates directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/monitoring/grafana"
    state: directory
    mode: 0755

- name: Create prometheus.yml from template
  template:
    src: prometheus.yml.j2
    dest: "/home/{{ env.SYS_USER }}/server/monitoring/prometheus/prometheus.yml"

- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ env.SYS_USER }}/server/monitoring/docker-compose.yml"

- name: Deploy Monitoring Stack
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/monitoring/"
  become: yes
  become_method: sudo 