- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/data"
    - "{{ role_name }}/foundrydl"

- name: Copy zip
  copy:
    src: FoundryVTT-9.269.zip
    dest: "/home/{{ SYS_USER }}/server/foundry/foundrydl/FoundryVTT.zip"

- include_tasks: dns.yml
  with_items:
    - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
