- name: Create sonarr directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/sonarr/config"
    state: directory
    mode: 0755

- name: Create download directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/library/downloads"
    state: directory
    mode: 0755

- name: Create tv directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/library/tvseries"
    state: directory
    mode: 0755

- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ env.SYS_USER }}/server/sonarr/docker-compose.yml"
    
- name: Deploy Sonarr
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/sonarr/"
  become: yes
  become_method: sudo