- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/config"
    - "media/downloads"
    - "media/tvseries"

- name: Create cleaner from template
  template:
    src: sonarr-episode-trimmer.py.j2
    dest: "/home/{{ SYS_USER }}/server/sonarr/config/sonarr-episode-trimmer.py"
    mode: 0755

- name: Create cleaner config from template
  template:
    src: sonarr-episode-trimmer-config.j2
    dest: "/home/{{ SYS_USER }}/server/sonarr/config/sonarr-episode-trimmer-config"
    mode: 0755

- include_tasks: dns.yml
  with_items:
    - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
