- name: Create sonarr directories
  file:
    path: "/home/{{ SYS_USER }}/server/sonarr/config"
    state: directory
    mode: 0755

- name: Create download directories
  file:
    path: "/home/{{ SYS_USER }}/server/media/downloads"
    state: directory
    mode: 0755

- name: Create tv directories
  file:
    path: "/home/{{ SYS_USER }}/server/media/tvseries"
    state: directory
    mode: 0755

- name: Create cleaner from template
  template:
    src: sonarr-episode-trimmer.py.j2
    dest: "/home/{{ SYS_USER }}/server/sonarr/config/sonarr-episode-trimmer.py"
    mode: 0755

- name: Create cleaner config from template
  template:
    src: sonarr-episode-trimmer-config.j2
    dest: "/home/{{ SYS_USER }}/server/sonarr/config/sonarr-episode-trimmer-config"
    mode: 0755

- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ SYS_USER }}/server/sonarr/docker-compose.yml"
    
- name: Deploy Sonarr
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ SYS_USER }}/server/sonarr/"
  become: yes
  become_method: sudo