- name: Create prowlarr directories
  file:
    path: "/home/{{ SYS_USER }}/server/prowlarr/config"
    state: directory
    mode: 0755

- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ SYS_USER }}/server/prowlarr/docker-compose.yml"
    
- name: Deploy Prowlarr
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ SYS_USER }}/server/prowlarr/"
  become: yes
  become_method: sudo