- name: Create config directory
  file:
    path: "/home/{{ env.SYS_USER }}/syncthing/config"
    state: directory
    mode: 0755

- name: Create data1 directory
  file:
    path: "/home/{{ env.SYS_USER }}/syncthing/config"
    state: directory
    mode: 0755

- name: Create data2 directory
  file:
    path: "/home/{{ env.SYS_USER }}/syncthing/config"
    state: directory
    mode: 0755
  
- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ env.SYS_USER }}/syncthing/docker-compose.yml"
    
- name: Deploy Syncthing
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/syncthing/"
  become: yes
  become_method: sudo