- include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    dirs_to_create:
    - "{{ container_item.name }}/config"
    - "{{ container_item.name }}/icons"

- name: Copy Icons
  copy:
    src: "{{ item }}"
    dest: "/home/{{ SYS_USER }}/server/containers/{{ role_name }}/icons/{{ item }}"
  with_items:
    - opgg.png
    - tacticstools.png

- name: Copy Config files
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ SYS_USER }}/server/containers/{{ role_name }}/config/{{ item }}"
  with_items:
    - settings.yaml
    - bookmarks.yaml
    - services.yaml
    - widgets.yaml
    - docker.yaml

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_role:
    name: common
    tasks_from: docker_deploy.yml
