---
- name: Create required directories
  ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    common_dirs_to_create:
      - "{{ container_item.name }}/config"
      - "{{ container_item.name }}/icons"

- name: Copy Icons
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ sys_user }}/server/containers/{{ role_name }}/icons/{{ item }}"
    mode: "0664"
  with_items:
    - opgg.png
    - tacticstools.png

- name: Copy Config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ sys_user }}/server/containers/{{ role_name }}/config/{{ item }}"
    mode: "0664"
  with_items:
    - settings.yaml
    - bookmarks.yaml
    - services.yaml
    - widgets.yaml
    - docker.yaml
    - custom.css

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml
