#!/usr/bin/env python3
"""PreToolUse(Bash) guard: the two file rules that only ever watched the Edit tool.

WHY A SECOND SURFACE. `block-protected-edits.py` denies edits to the generated `containers/`
tree, to generated docs pages, and to SOPS-encrypted files — but it is wired at matcher
`Edit|Write|MultiEdit|NotebookEdit`, and auto mode injects a standing instruction telling the
model to make file changes "with sed, heredocs, or short scripts, rather than using the
dedicated Read, Edit, or Write tools". The instructed path was the unguarded one. Measured
2026-08-29: `sed -i s/a/b/ ansible/vars/secrets.yml`, `cat > containers/glances/
docker-compose.yml` and `tee docs/reference/services.md` each returned NO decision from both
PreToolUse Bash hooks. `bash-write-fanout.sh` already closes this gap for the four PostToolUse
Edit|Write hooks; it does not re-drive a PreToolUse deny, so this does.

THREE ARMS, TWO DECISIONS, ON PURPOSE.

  1. WRITES -> `ask`, never `deny`. The path extraction here is a heuristic over command text,
     not a shell parse, and `bash-write-fanout.sh` states the bargain a heuristic has to keep:
     "The failure direction is a missed fanout, never a wrong one." A deny inverts that — one
     wrong extraction blocks legitimate work with no way around it. What was actually missing
     from the Bash path is the REASON: the permission prompt cannot say that a file is
     SOPS-encrypted or generated by a cron, and `classify()` can. `ask` carries the reason and
     leaves the decision where it belongs.

  2. READS of a deployed secret-bearing script -> `deny`. Different shape, so a different
     decision. `grep-on-a-script-prints-the-secret-it-embeds` records three occurrences, every
     one ending in a rotation, and the asymmetry is the whole argument: a hook can detect a
     token in a tool result but can never unwrite it, so the only control is not printing it.
     The reader must be in command position and the path must be one of ~15 files the tree
     itself names, so a false positive costs one narrower re-run while a false negative costs a
     rotation.

  3. WRITES THAT LEAVE AN ISOLATED SESSION'S WORKTREE -> `deny`. A different question from
     arm 1 — not WHICH file, but WHERE — so it takes the stronger decision. `isolation-guard.sh`
     denies an Edit or Write landing in a git checkout outside `.claude/worktrees/`, and it
     matches `Edit|Write|NotebookEdit` only, so the Bash surface auto mode instructs was
     uncovered. Measured 2026-09-06 18:17:54: a worktree-isolated agent ran
     `cd /home/ubuntu/server && python3 - <<'EOF' ... EOF`, the heredoc wrote to the PRIMARY
     checkout, and nothing stopped it. The stray edit left that tree dirty, which parked the
     GitOps deployer, and the agent's own verification grep ran under the same `cd` and read
     the escaped copy back — so the failure was silent from the inside. Issue #1419.

Reads the hook JSON on stdin. Emits a decision or stays silent -> normal permission flow.
"""

import importlib.util
import json
import os
import re
import sys

from _hook_common import emit_pretooluse_decision


def _load_classify():
    """`classify()` from block-protected-edits.py, loaded by path.

    The filename is hyphenated, so it is not importable by name — and renaming it would change
    the path settings.json invokes. One classifier serves both tool surfaces: a divergence
    between what the Edit hook denies and what this one flags is the failure this shares it to
    avoid.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    spec = importlib.util.spec_from_file_location(
        "block_protected_edits", os.path.join(here, "block-protected-edits.py")
    )
    assert spec and spec.loader, "spec_from_file_location found no loader"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.classify


classify = _load_classify()


# ── arm 1: writes ────────────────────────────────────────────────────────────────────
#
# The shapes a model's file write actually takes. Deliberately not a shell parser: a write
# inside `python3 -c` or a called script is invisible in the command text and is not detected.
# Each pattern captures the path in group 1.
_WRITE_SHAPES = (
    # `> path`, `>> path` — the redirect, by far the most common
    re.compile(r">>?\s*([^\s;&|<>()]+)"),
    # `tee path`, `tee -a path` — a pipe's write end
    re.compile(r"\btee\s+(?:-[^\s]+\s+)*([^\s;&|<>()]+)"),
    # `sed -i … path`, `perl -pi -e … path` — in-place editors, target last
    re.compile(
        r"\b(?:sed|perl)\b[^;&|]*?\s-[A-Za-z]*i(?:\.[^\s]*)?\s[^;&|]*?([^\s;&|<>()]+)\s*$"
    ),
)


def written_paths(command):
    """Candidate paths this command writes to. Best-effort, biased toward missing one."""
    found = []
    for line in command.splitlines():
        for shape in _WRITE_SHAPES:
            found.extend(m.group(1) for m in shape.finditer(line))
    # A heredoc delimiter and a process substitution are not paths; neither is a bare `-`.
    return [p for p in found if p not in ("-",) and not p.startswith(("$", "<", "("))]


# ── arm 2: reads that print file content ─────────────────────────────────────────────
#
# Readers whose output includes whole lines of the file. `grep` and friends are here because
# the recorded leak WAS a grep: a pattern need only match a line CARRYING a secret.
_CONTENT_READERS = (
    r"(cat|bat|head|tail|less|more|strings|xxd|od|nl|grep|egrep|rg|ag|awk)"
)

# The structure-only flags the memory prescribes as the safe form. `-o` is load-bearing: without
# it grep prints the whole matching line, key and value both. `-c`, `-l`, `-L` and `-q` emit a
# count, a filename or nothing, so none of them can carry a value out. The letter is looked for
# anywhere in the cluster, not at its end: `-oE` is the spelling the memory's own worked example
# uses, and a rule anchored on the last letter reads it as unsafe.
_STRUCTURE_LETTERS = set("oclLq")
_STRUCTURE_WORDS = {
    "--only-matching",
    "--count",
    "--files-with-matches",
    "--files-without-match",
    "--quiet",
    "--silent",
}
_FLAG = re.compile(r"^-{1,2}[A-Za-z][\w-]*$")

# Command position, the same anchoring block-dangerous-bash.sh uses and for the same reason:
# `grep -n "cat /usr/local/bin/secret-rotate.sh" notes.md` is text describing the command.
_CMD_AT = r"(^|[;&|(`])\s*([A-Za-z_][A-Za-z0-9_]*=[^\s]*\s+)*"
# `[^;&]*` deliberately spans `|`. A pipe separates commands, but it also appears INSIDE a grep
# alternation — `grep -nE "rotate|--commit|sops set|push" <path>` is the incident's own command,
# and stopping at the first `|` cut the path off before the match could see it.
_READER_RE = re.compile(_CMD_AT + r"(sudo\s+)?" + _CONTENT_READERS + r"\b([^;&]*)")


def prints_whole_lines(args):
    """True unless the reader's own flags reduce its output to structure.

    Only the leading run of options counts. A `-o` further down the line belongs to a later
    command in a pipeline — `cat <path> | grep -o X` has already printed the file by then.
    """
    for token in args.split():
        if not _FLAG.match(token):
            break
        if token in _STRUCTURE_WORDS:
            return False
        if not token.startswith("--") and _STRUCTURE_LETTERS & set(token[1:]):
            return False
    return True


# Cheap gate. The derivation below walks every role task file (~0.9s), which is far too slow to
# run on every Bash call — and every path it can return starts with one of these two prefixes.
_HOST_BIN_PREFIXES = ("/usr/local/bin", "/opt/homelab")


def _secret_bearing_paths(repo_root):
    """The derived host-path set, or {} if it cannot be computed.

    Import is deferred so the hot path never pays for it — see the cheap gate above.
    """
    scripts = os.path.join(repo_root, "scripts", "secrets_mgmt")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    try:
        from secret_bearing_host_paths import secret_bearing_host_paths

        return secret_bearing_host_paths()
    except Exception:
        # A guard in front of every Bash call must fail open when it cannot compute its answer.
        # The alternative is a session where nothing runs because a YAML file moved.
        return {}


def read_reason(command, repo_root):
    """A deny reason if this command prints the content of a secret-bearing host script."""
    if not any(prefix in command for prefix in _HOST_BIN_PREFIXES):
        return None
    paths = None
    for line in command.splitlines():
        for match in _READER_RE.finditer(line):
            reader, args = match.group(4), match.group(5)
            if not prints_whole_lines(args):
                continue
            if paths is None:
                paths = _secret_bearing_paths(repo_root)
            for dest, names in paths.items():
                if dest in args:
                    return (
                        f"`{dest}` renders {', '.join(names)} inline, so `{reader}` on it "
                        f"prints the credential into the terminal and the transcript — which "
                        f"cannot be scrubbed, only rotated. Print structure instead: "
                        f"`grep -oE '^[A-Z_]+=' {dest}`, or `ssh-keygen -lf` for a key. "
                        f"See memory: grep-on-a-script-prints-the-secret-it-embeds."
                    )
    return None


# ── arm 3: a write that escapes an isolated session's worktree ───────────────────────
#
# Scoped to a session whose cwd is itself under `.claude/worktrees/`. Outside one this arm is
# inert, so an ordinary session in the primary checkout is untouched.

# The marker `isolation-guard.sh` uses, spelled with separators on both sides so a directory
# merely NAMED worktrees does not match.
_WORKTREES = f"{os.sep}.claude{os.sep}worktrees{os.sep}"

# Command words that take a heredoc and then write files the command text never names. This is
# the incident's own shape: `python3 - <<'EOF'` carries no redirect, so `written_paths` returns
# nothing and there is no target to judge — only the directory the write lands in.
# `uv` is here because `uv run python - <<EOF` is how this repo invokes its pinned interpreter.
_HEREDOC_INTERPRETERS = frozenset(
    {"python", "python3", "bash", "sh", "zsh", "perl", "ruby", "node", "uv"}
)

_HEREDOC_OPEN = re.compile(r"<<-?\s*[\"']?([A-Za-z_][A-Za-z0-9_-]*)")
_CD = re.compile(r"^\s*(?:cd|pushd)\s+([^\s;&|<>()]+)\s*$")
_ENV_ASSIGN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
# `||` and `&&` first, so the two-character operators are not split as two one-character ones.
_SEGMENTS = re.compile(r"\s*(?:\|\||&&|[;|&\n])\s*")


def strip_heredoc_bodies(command):
    """Drop every heredoc BODY, keeping the line that opens it.

    This has to happen before anything scans for `>`, and `bash-write-fanout.sh` records why:
    file content is not shell, so a Markdown blockquote line inside the body is a bare `>` and
    the redirect scan reads a filename out of the prose. The opening line survives, so both the
    `> file` that names a real target and the `<<EOF` that names an interpreter are still seen.
    """
    kept = []
    delim = None
    for line in command.splitlines():
        if delim is not None:
            if line.strip() == delim:
                delim = None
            continue
        kept.append(line)
        match = _HEREDOC_OPEN.search(line)
        if match:
            delim = match.group(1)
    return "\n".join(kept)


def _in_a_worktree(path):
    return _WORKTREES in os.path.abspath(path) + os.sep


def _inside_a_git_checkout(path):
    """True if `path` sits under a directory holding a `.git`.

    Pure filesystem, no subprocess: this runs in front of every Bash call. A path outside any
    repo — /tmp, a scratch directory, ~/.claude/artifacts — is not a checkout edit and is left
    alone, the same scope `isolation-guard.sh` states.
    """
    current = os.path.abspath(path)
    while True:
        if os.path.exists(os.path.join(current, ".git")):
            return True
        parent = os.path.dirname(current)
        if parent == current:
            return False
        current = parent


def _escapes(path):
    """True if a write to `path` lands in a git checkout outside any `.claude/worktrees/`."""
    return not _in_a_worktree(path) and _inside_a_git_checkout(path)


def _heredoc_interpreter(segment):
    """The interpreter this segment feeds a heredoc to, or None."""
    if "<<" not in segment:
        return None
    for token in segment.split():
        if _ENV_ASSIGN.match(token):
            continue
        word = os.path.basename(token)
        return word if word in _HEREDOC_INTERPRETERS else None
    return None


def escaping_write_reason(command, session_cwd):
    """A deny reason if this command writes outside the worktree the session is isolated in.

    Walks the command a segment at a time, carrying the directory a leading `cd` or `pushd`
    moves it to — that carry is the whole point, because the incident's relative writes were
    only outside the worktree by virtue of the `cd` in front of them.

    Two verdicts per segment, and the split is what keeps this from over-denying. When the
    segment names write targets, those targets are judged, so `cd /home/ubuntu/server &&
    cat foo > /tmp/x` stays clean. Only when a writer is present and names nothing — the
    interpreter-heredoc case — does the effective directory decide.
    """
    if not _in_a_worktree(session_cwd):
        return None
    cwd = os.path.abspath(session_cwd)
    for segment in _SEGMENTS.split(strip_heredoc_bodies(command)):
        if not segment.strip():
            continue
        moved = _CD.match(segment)
        if moved:
            destination = moved.group(1).strip("\"'")
            if "$" in destination or destination == "-":
                # An unresolvable destination: every later segment's directory is unknown, so
                # stop rather than judge against a directory the command is not in.
                return None
            cwd = os.path.abspath(os.path.join(cwd, os.path.expanduser(destination)))
            continue
        targets = [p.strip("\"'") for p in written_paths(segment)]
        if targets:
            for target in targets:
                resolved = (
                    target if os.path.isabs(target) else os.path.join(cwd, target)
                )
                if _escapes(resolved):
                    return (
                        f"`{os.path.abspath(resolved)}` is in a git checkout outside "
                        f"`.claude/worktrees/`, and this session is isolated in "
                        f"{session_cwd}. Write inside the worktree instead. If the edit "
                        f"genuinely belongs to another checkout, make it from a session "
                        f"that is not worktree-isolated. See issue #1419."
                    )
            continue
        interpreter = _heredoc_interpreter(segment)
        if interpreter and _escapes(cwd):
            return (
                f"This command runs `{interpreter}` on a heredoc from {cwd}, a git checkout "
                f"outside `.claude/worktrees/`, while this session is isolated in "
                f"{session_cwd}. The heredoc names no target, so the directory it runs in "
                f"decides where its writes land — that is how a stray edit reached the "
                f"primary checkout and parked the GitOps deployer on 2026-09-06. Drop the "
                f"`cd` and write inside the worktree. See issue #1419."
            )
    return None


def decide(command, repo_root, session_cwd=None):
    """Return (decision, reason), or (None, None) for normal permission flow.

    `session_cwd` is the directory the tool call runs in, which arm 3 reads to tell an isolated
    session from an ordinary one. It defaults to `repo_root` because the payload supplies one
    value for both; the tests pass them separately so arm 3's scoping is provable in CI, where
    the checkout is not under `.claude/worktrees/`.
    """
    # DECIDED: arm 3 runs FIRST, and denies where arm 1 only asks. `cd /home/ubuntu/server &&
    # sed -i s/a/b/ ansible/vars/secrets.yml` matches both, and an `ask` there would let the
    # escape be approved on the strength of a prompt about the wrong thing. The asymmetry
    # arm 1's docstring argues does not apply here: a heuristic that wrongly asks costs a
    # prompt, but a write outside an isolated session's worktree is never the right call, so
    # a wrong deny costs one re-run from the right directory while a wrong allow parks the
    # deployer for every session. The known cost is that a deliberate edit to the chezmoi
    # checkout from a server worktree is denied; the reason string names the way through.
    escaped = escaping_write_reason(command, session_cwd or repo_root)
    if escaped:
        return "deny", escaped
    reason = read_reason(command, repo_root)
    if reason:
        return "deny", reason
    for path in written_paths(command):
        target = path if os.path.isabs(path) else os.path.join(repo_root, path)
        write_reason = classify(target, repo_root)
        if write_reason:
            return (
                "ask",
                f"This Bash command writes to a protected file. {write_reason}",
            )
    return None, None


def main():
    """Read the hook payload from stdin and gate a Bash command via `decide`.

    Emits the PreToolUse deny or ask decision `decide` returns; ignores non-Bash tool
    calls and commands `decide` has no opinion on. Always returns 0.
    """
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0
    if data.get("tool_name") != "Bash":
        return 0
    command = (data.get("tool_input") or {}).get("command") or ""
    if not command:
        return 0
    repo_root = data.get("cwd") or os.getcwd()
    decision, reason = decide(command, repo_root)
    if decision:
        emit_pretooluse_decision(decision, reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())
