#!/usr/bin/env python3
"""PreToolUse(Edit|Write) guard: deny direct edits to files you must not edit by hand.

Two classes, both always a mistake in this repo:

  1. Anything under `containers/` — generated and deployed by Ansible from
     `ansible/roles/containers/*/templates/`. A direct edit is silently overwritten
     on the next deploy. (CLAUDE.md / `.claude/rules/docker.md`.)

  2. A SOPS-encrypted file (e.g. `ansible/vars/secrets.yml`) — editing the ciphertext
     corrupts it, and pasting a plaintext secret in risks committing it. You must go
     through `sops`. (`.claude/rules/secrets.md`.) Detection is CONTENT-based, not
     path-based: `host_vars/*.yml` / `group_vars/all.yml` contain the substring
     "vars/" but are PLAINTEXT and must stay editable. It keys off the SOPS integrity
     MAC field (a `mac:` metadata line) — NOT a bare ciphertext substring, so a file
     that merely *mentions* the marker (a doc, a test, this hook) is not misclassified.

Reads the hook JSON on stdin. Emits a PreToolUse "deny" decision when the target is
one of the above; otherwise no output -> normal permission flow. The hook can only
ever BLOCK; it never approves.
"""
import json
import os
import re
import sys


_SOPS_MAC_RE = re.compile(r'(?m)^\s*"?mac"?:\s*"?ENC\[AES256_GCM,')


def is_sops_encrypted(text):
    """True iff text is a SOPS-encrypted document. Keys off the structural integrity
    MAC field in the sops metadata block (a `mac:` line whose value is AES256-GCM
    ciphertext) rather than the bare marker substring — so a file that merely mentions
    the marker (docs, tests, this progress log) is not misclassified as ciphertext."""
    return bool(_SOPS_MAC_RE.search(text))


def _read_file(path, limit=1_048_576):
    """Read a file's text for marker detection. SOPS keeps its integrity MAC in the
    metadata block at the END of the file, so we read the whole thing (capped — a real
    secrets file is small; anything over the cap is not one). Missing/binary -> ''."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read(limit)
    except OSError:
        return ""


def classify(file_path, repo_root):
    """Return a deny reason if file_path must not be edited directly, else None.

    Relative paths resolve against repo_root (the session cwd). The containers check
    is a pure path-segment match; the SOPS check reads the target's content.
    """
    if not file_path:
        return None
    target = file_path if os.path.isabs(file_path) else os.path.join(repo_root, file_path)
    target = os.path.normpath(target)

    # 1. generated containers/ tree
    guard = os.path.normpath(os.path.join(repo_root, "containers"))
    if target == guard or target.startswith(guard + os.sep):
        rel = os.path.relpath(target, guard)
        service = rel.split(os.sep, 1)[0] if rel not in (".", "") else "<service>"
        return (
            f"`containers/` is generated by Ansible — direct edits are overwritten on "
            f"the next deploy. Edit the template instead: "
            f"ansible/roles/containers/{service}/templates/ "
            f"(see CLAUDE.md → Directory Structure)."
        )

    # 2. SOPS-encrypted file (content-based)
    if is_sops_encrypted(_read_file(target)):
        rel = os.path.relpath(target, repo_root) if target.startswith(repo_root + os.sep) else target
        return (
            f"`{rel}` is SOPS-encrypted — don't edit it directly (you'd corrupt the "
            f"ciphertext or commit a plaintext secret). Edit it via `sops {rel}`, or use "
            f"the /add-secret skill. See .claude/rules/secrets.md."
        )
    return None


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0
    file_path = ((data.get("tool_input") or {}).get("file_path")) or ""
    # repo_root = two levels up from .claude/hooks/
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    reason = classify(file_path, repo_root)
    if reason:
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason,
            }
        }))
    return 0


if __name__ == "__main__":
    sys.exit(main())
