#!/usr/bin/env python3
"""PreToolUse(Edit|Write) guard: deny edits under `containers/`.

`containers/` is generated and deployed by Ansible from templates in
`ansible/roles/containers/*/templates/`. A direct edit there is silently
overwritten on the next deploy — pure wasted work. CLAUDE.md and
`.claude/rules/docker.md` say "NEVER edit files inside containers/"; this hook
makes that a hard deny instead of a soft instruction.

Reads the hook JSON on stdin. Emits a PreToolUse "deny" decision iff the target
file_path lands under <repo>/containers/. Anything else -> no output -> normal
permission flow. The hook can only ever BLOCK writes to generated files; it never
approves anything.
"""
import json
import os
import sys


def classify(file_path, repo_root):
    """Return a deny reason if file_path is under <repo_root>/containers/, else None.

    Pure function (no I/O) so it is table-testable. Relative paths are resolved
    against repo_root (the session cwd during a deploy). Uses a path-segment
    boundary so a look-alike sibling like `containers-notes/` is NOT blocked.
    """
    if not file_path:
        return None
    target = file_path if os.path.isabs(file_path) else os.path.join(repo_root, file_path)
    target = os.path.normpath(target)
    guard = os.path.normpath(os.path.join(repo_root, "containers"))
    if target == guard or target.startswith(guard + os.sep):
        rel = os.path.relpath(target, guard)
        service = rel.split(os.sep, 1)[0] if rel not in (".", "") else "<service>"
        return (
            f"`containers/` is generated by Ansible — direct edits are overwritten on "
            f"the next deploy. Edit the template instead: "
            f"ansible/roles/containers/{service}/templates/ "
            f"(see .claude/rules/docker.md)."
        )
    return None


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0
    file_path = ((data.get("tool_input") or {}).get("file_path")) or ""
    # repo_root = two levels up from .claude/hooks/
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    reason = classify(file_path, repo_root)
    if reason:
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason,
            }
        }))
    return 0


if __name__ == "__main__":
    sys.exit(main())
