#!/usr/bin/env python3
"""PreToolUse(Bash) guard: the two file rules that only ever watched the Edit tool.

WHY A SECOND SURFACE. `block-protected-edits.py` denies edits to the generated `containers/`
tree, to generated docs pages, and to SOPS-encrypted files — but it is wired at matcher
`Edit|Write|MultiEdit|NotebookEdit`, and auto mode injects a standing instruction telling the
model to make file changes "with sed, heredocs, or short scripts, rather than using the
dedicated Read, Edit, or Write tools". The instructed path was the unguarded one. Measured
2026-08-29: `sed -i s/a/b/ ansible/vars/secrets.yml`, `cat > containers/glances/
docker-compose.yml` and `tee docs/reference/services.md` each returned NO decision from both
PreToolUse Bash hooks. `bash-write-fanout.sh` already closes this gap for the four PostToolUse
Edit|Write hooks; it does not re-drive a PreToolUse deny, so this does.

TWO ARMS, TWO DECISIONS, ON PURPOSE.

  1. WRITES -> `ask`, never `deny`. The path extraction here is a heuristic over command text,
     not a shell parse, and `bash-write-fanout.sh` states the bargain a heuristic has to keep:
     "The failure direction is a missed fanout, never a wrong one." A deny inverts that — one
     wrong extraction blocks legitimate work with no way around it. What was actually missing
     from the Bash path is the REASON: the permission prompt cannot say that a file is
     SOPS-encrypted or generated by a cron, and `classify()` can. `ask` carries the reason and
     leaves the decision where it belongs.

  2. READS of a deployed secret-bearing script -> `deny`. Different shape, so a different
     decision. `grep-on-a-script-prints-the-secret-it-embeds` records three occurrences, every
     one ending in a rotation, and the asymmetry is the whole argument: a hook can detect a
     token in a tool result but can never unwrite it, so the only control is not printing it.
     The reader must be in command position and the path must be one of ~15 files the tree
     itself names, so a false positive costs one narrower re-run while a false negative costs a
     rotation.

Reads the hook JSON on stdin. Emits a decision or stays silent -> normal permission flow.
"""

import importlib.util
import json
import os
import re
import sys

from _hook_common import emit_pretooluse_decision


def _load_classify():
    """`classify()` from block-protected-edits.py, loaded by path.

    The filename is hyphenated, so it is not importable by name — and renaming it would change
    the path settings.json invokes. One classifier serves both tool surfaces: a divergence
    between what the Edit hook denies and what this one flags is the failure this shares it to
    avoid.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    spec = importlib.util.spec_from_file_location(
        "block_protected_edits", os.path.join(here, "block-protected-edits.py")
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.classify


classify = _load_classify()


# ── arm 1: writes ────────────────────────────────────────────────────────────────────
#
# The shapes a model's file write actually takes. Deliberately not a shell parser: a write
# inside `python3 -c` or a called script is invisible in the command text and is not detected.
# Each pattern captures the path in group 1.
_WRITE_SHAPES = (
    # `> path`, `>> path` — the redirect, by far the most common
    re.compile(r">>?\s*([^\s;&|<>()]+)"),
    # `tee path`, `tee -a path` — a pipe's write end
    re.compile(r"\btee\s+(?:-[^\s]+\s+)*([^\s;&|<>()]+)"),
    # `sed -i … path`, `perl -pi -e … path` — in-place editors, target last
    re.compile(
        r"\b(?:sed|perl)\b[^;&|]*?\s-[A-Za-z]*i(?:\.[^\s]*)?\s[^;&|]*?([^\s;&|<>()]+)\s*$"
    ),
)


def written_paths(command):
    """Candidate paths this command writes to. Best-effort, biased toward missing one."""
    found = []
    for line in command.splitlines():
        for shape in _WRITE_SHAPES:
            found.extend(m.group(1) for m in shape.finditer(line))
    # A heredoc delimiter and a process substitution are not paths; neither is a bare `-`.
    return [p for p in found if p not in ("-",) and not p.startswith(("$", "<", "("))]


# ── arm 2: reads that print file content ─────────────────────────────────────────────
#
# Readers whose output includes whole lines of the file. `grep` and friends are here because
# the recorded leak WAS a grep: a pattern need only match a line CARRYING a secret.
_CONTENT_READERS = (
    r"(cat|bat|head|tail|less|more|strings|xxd|od|nl|grep|egrep|rg|ag|awk)"
)

# The structure-only flags the memory prescribes as the safe form. `-o` is load-bearing: without
# it grep prints the whole matching line, key and value both. `-c`, `-l`, `-L` and `-q` emit a
# count, a filename or nothing, so none of them can carry a value out. The letter is looked for
# anywhere in the cluster, not at its end: `-oE` is the spelling the memory's own worked example
# uses, and a rule anchored on the last letter reads it as unsafe.
_STRUCTURE_LETTERS = set("oclLq")
_STRUCTURE_WORDS = {
    "--only-matching",
    "--count",
    "--files-with-matches",
    "--files-without-match",
    "--quiet",
    "--silent",
}
_FLAG = re.compile(r"^-{1,2}[A-Za-z][\w-]*$")

# Command position, the same anchoring block-dangerous-bash.sh uses and for the same reason:
# `grep -n "cat /usr/local/bin/secret-rotate.sh" notes.md` is text describing the command.
_CMD_AT = r"(^|[;&|(`])\s*([A-Za-z_][A-Za-z0-9_]*=[^\s]*\s+)*"
# `[^;&]*` deliberately spans `|`. A pipe separates commands, but it also appears INSIDE a grep
# alternation — `grep -nE "rotate|--commit|sops set|push" <path>` is the incident's own command,
# and stopping at the first `|` cut the path off before the match could see it.
_READER_RE = re.compile(_CMD_AT + r"(sudo\s+)?" + _CONTENT_READERS + r"\b([^;&]*)")


def prints_whole_lines(args):
    """True unless the reader's own flags reduce its output to structure.

    Only the leading run of options counts. A `-o` further down the line belongs to a later
    command in a pipeline — `cat <path> | grep -o X` has already printed the file by then.
    """
    for token in args.split():
        if not _FLAG.match(token):
            break
        if token in _STRUCTURE_WORDS:
            return False
        if not token.startswith("--") and _STRUCTURE_LETTERS & set(token[1:]):
            return False
    return True


# Cheap gate. The derivation below walks every role task file (~0.9s), which is far too slow to
# run on every Bash call — and every path it can return starts with one of these two prefixes.
_HOST_BIN_PREFIXES = ("/usr/local/bin", "/opt/homelab")


def _secret_bearing_paths(repo_root):
    """The derived host-path set, or {} if it cannot be computed.

    Import is deferred so the hot path never pays for it — see the cheap gate above.
    """
    scripts = os.path.join(repo_root, "scripts", "secrets_mgmt")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    try:
        from secret_bearing_host_paths import secret_bearing_host_paths

        return secret_bearing_host_paths()
    except Exception:
        # A guard in front of every Bash call must fail open when it cannot compute its answer.
        # The alternative is a session where nothing runs because a YAML file moved.
        return {}


def read_reason(command, repo_root):
    """A deny reason if this command prints the content of a secret-bearing host script."""
    if not any(prefix in command for prefix in _HOST_BIN_PREFIXES):
        return None
    paths = None
    for line in command.splitlines():
        for match in _READER_RE.finditer(line):
            reader, args = match.group(4), match.group(5)
            if not prints_whole_lines(args):
                continue
            if paths is None:
                paths = _secret_bearing_paths(repo_root)
            for dest, names in paths.items():
                if dest in args:
                    return (
                        f"`{dest}` renders {', '.join(names)} inline, so `{reader}` on it "
                        f"prints the credential into the terminal and the transcript — which "
                        f"cannot be scrubbed, only rotated. Print structure instead: "
                        f"`grep -oE '^[A-Z_]+=' {dest}`, or `ssh-keygen -lf` for a key. "
                        f"See memory: grep-on-a-script-prints-the-secret-it-embeds."
                    )
    return None


def decide(command, repo_root):
    """Return (decision, reason), or (None, None) for normal permission flow."""
    reason = read_reason(command, repo_root)
    if reason:
        return "deny", reason
    for path in written_paths(command):
        target = path if os.path.isabs(path) else os.path.join(repo_root, path)
        write_reason = classify(target, repo_root)
        if write_reason:
            return (
                "ask",
                f"This Bash command writes to a protected file. {write_reason}",
            )
    return None, None


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0
    if data.get("tool_name") != "Bash":
        return 0
    command = (data.get("tool_input") or {}).get("command") or ""
    if not command:
        return 0
    repo_root = data.get("cwd") or os.getcwd()
    decision, reason = decide(command, repo_root)
    if decision:
        emit_pretooluse_decision(decision, reason)
    return 0


if __name__ == "__main__":
    sys.exit(main())
