#!/usr/bin/env python3
"""Table-driven tests for the block-protected-edits PreToolUse guard.

The guard denies two classes of direct edit that are always a mistake here:
  1. anything under `containers/` — generated by Ansible, overwritten on deploy.
  2. a SOPS-encrypted file — editing ciphertext corrupts it / risks committing a
     plaintext secret; you must go through `sops`.

The SOPS check is CONTENT-based, not path-based: `host_vars/*.yml` and
`group_vars/all.yml` contain the substring "vars/" but are PLAINTEXT and must stay
editable, so the guard keys off the file's actual `ENC[AES256_GCM` markers.

Run: uv run pytest .claude/hooks
"""
import importlib.util
import os

_HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "block-protected-edits.py")
_spec = importlib.util.spec_from_file_location("block_protected_edits", _HOOK)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
classify = _mod.classify
is_sops_encrypted = _mod.is_sops_encrypted

# Repo root derived from THIS file's location (.claude/hooks/), NOT hardcoded — the test must
# work in any checkout, incl. CI's /home/runner/work/... A hardcoded /home/ubuntu/server made
# classify() read a nonexistent secrets.yml in CI -> None -> a false `test_blocks_the_real_secrets_file`
# failure. Mirrors the hook's own repo_root computation in block-protected-edits.py.
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# --- containers guard (regression — unchanged behavior) ---------------------

BLOCK_CONTAINERS = [
    ("containers/jellyfin/docker-compose.yml", "relative path in containers"),
    (os.path.join(REPO, "containers/jellyfin/docker-compose.yml"), "absolute path"),
    ("containers", "the containers dir itself"),
    ("ansible/../containers/foo.yml", "path that normalizes into containers"),
]

ALLOW_NONCONTAINERS = [
    ("ansible/roles/containers/jellyfin/templates/docker-compose.yml.j2", "the template"),
    ("scripts/probe.py", "a script"),
    ("CLAUDE.md", "repo root file"),
    ("containers-notes/readme.md", "sibling that only shares a prefix"),
]


def test_blocks_writes_under_containers():
    for path, label in BLOCK_CONTAINERS:
        assert classify(path, REPO) is not None, f"should BLOCK: {label} ({path!r})"


def test_allows_writes_elsewhere():
    for path, label in ALLOW_NONCONTAINERS:
        assert classify(path, REPO) is None, f"should ALLOW: {label} ({path!r})"


def test_containers_reason_points_at_template_dir():
    reason = classify("containers/jellyfin/docker-compose.yml", REPO)
    assert "ansible/roles/containers" in reason


# --- SOPS content detection (pure) ------------------------------------------
# Fixtures are built by concatenation so a SOPS signature never appears as a
# contiguous string in THIS source file — otherwise the guard would block editing
# this very test. _ENC keeps "ENC[" + "AES256_GCM" split across the +; the encrypted
# fixture carries a `mac:` metadata line (the structural signal the guard keys off).
_ENC = "ENC[" + "AES256_GCM,data:Zz==,iv:Yy=,tag:Xx==,type:str]"
SOPS_TEXT = (
    "db_password: " + _ENC + "\n"
    "sops:\n"
    '    lastmodified: "2026-06-15T13:17:13Z"\n'
    "    mac: " + _ENC + "\n"
    "    version: 3.9.2\n"
)
PLAINTEXT_HOST_VARS = "server_ip: 10.0.0.161\ncontainers_list:\n  - name: jellyfin\n"
# A doc/log that merely *mentions* the marker in prose — must NOT be flagged. This is
# the iteration-3 regression: the bare-substring check wrongly blocked such files.
PROSE_MENTIONING_MARKER = "Detection keys off the file's " + "ENC[" + "AES256_GCM markers.\n"


def test_is_sops_encrypted_true_on_real_sops_metadata():
    assert is_sops_encrypted(SOPS_TEXT) is True


def test_is_sops_encrypted_false_on_plaintext():
    assert is_sops_encrypted(PLAINTEXT_HOST_VARS) is False
    assert is_sops_encrypted("") is False


def test_is_sops_encrypted_false_on_prose_mention():
    # regression: a file that only TALKS about the marker is plaintext, not encrypted.
    assert is_sops_encrypted(PROSE_MENTIONING_MARKER) is False


# --- SOPS guard via classify (content-based, hermetic via tmp files) --------

def test_blocks_edit_of_encrypted_file(tmp_path):
    f = tmp_path / "secrets.yml"
    f.write_text(SOPS_TEXT)
    reason = classify(str(f), REPO)
    assert reason is not None and "sops" in reason.lower(), "must block + mention sops"


def test_allows_edit_of_plaintext_yaml_that_path_pattern_would_catch(tmp_path):
    # name it like host_vars to prove the guard is content-based, not path-based
    d = tmp_path / "host_vars"
    d.mkdir()
    f = d / "daniel-server.yml"
    f.write_text(PLAINTEXT_HOST_VARS)
    assert classify(str(f), REPO) is None, "plaintext vars file must stay editable"


def test_nonexistent_file_does_not_crash():
    assert classify(os.path.join(REPO, "does/not/exist.yml"), REPO) is None


def test_blocks_the_real_secrets_file():
    # integration: the repo's actual encrypted secrets file must be blocked.
    assert classify("ansible/vars/secrets.yml", REPO) is not None
