#!/usr/bin/env python3
"""Table-driven tests for the block-containers-edit PreToolUse guard.

The guard enforces the repo's #1 rule — `containers/` is generated by Ansible and
direct edits are silently overwritten on the next deploy. The hook turns that prose
rule into a hard deny. These tables lock the contract: every write under
`containers/` is blocked, everything else is left alone (no output -> normal flow).

Run: uv run pytest .claude/hooks
(Importable standalone — loads the hook by path, no third-party deps.)
"""
import importlib.util
import os

_HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "block-containers-edit.py")
_spec = importlib.util.spec_from_file_location("block_containers_edit", _HOOK)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
classify = _mod.classify

REPO = "/home/ubuntu/server"

# MUST block: any write that lands under <repo>/containers/.
BLOCK = [
    ("containers/jellyfin/docker-compose.yml", "relative path in containers"),
    ("./containers/jellyfin/docker-compose.yml", "dot-relative path"),
    ("/home/ubuntu/server/containers/jellyfin/docker-compose.yml", "absolute path"),
    ("containers/new-service/.env", "new file under containers"),
    ("containers", "the containers dir itself"),
    ("ansible/../containers/foo.yml", "path that normalizes into containers"),
]

# MUST allow (no block): writes anywhere else, including look-alike siblings.
ALLOW = [
    ("ansible/roles/containers/jellyfin/templates/docker-compose.yml.j2", "the template — the right place to edit"),
    ("scripts/probe.py", "a script"),
    ("CLAUDE.md", "repo root file"),
    ("containers-notes/readme.md", "sibling dir that only shares a prefix"),
    ("/etc/hosts", "absolute path outside the repo"),
    ("", "empty path"),
]


def test_blocks_writes_under_containers():
    for path, label in BLOCK:
        assert classify(path, REPO) is not None, f"should BLOCK: {label} ({path!r})"


def test_allows_writes_elsewhere():
    for path, label in ALLOW:
        assert classify(path, REPO) is None, f"should ALLOW: {label} ({path!r})"


def test_block_reason_points_at_template_dir():
    reason = classify("containers/jellyfin/docker-compose.yml", REPO)
    assert "ansible/roles/containers" in reason, "deny reason must redirect to the template"
