---
- name: Create required directories
  ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    common_dirs_to_create:
      - "{{ container_item.name }}/app"

- name: Copy App Code
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ sys_user }}/server/containers/{{ role_name }}/app/{{ item }}"
    mode: "0664"
  with_items:
    - app.py

- name: Copy Docker files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ sys_user }}/server/containers/{{ role_name }}/{{ item }}"
    mode: "0664"
  with_items:
    - docker-compose.yml
    - Dockerfile

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml
