- include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    dirs_to_create:
    - "{{ container_item.name }}/config/notifications"

- name: Create acquis.yaml from template
  template:
    src: acquis.yaml.j2
    dest: "/home/{{ SYS_USER }}/server/containers/crowdsec/config/acquis.yaml"

- name: Copy profiles.yaml
  copy:
    src: profiles.yaml
    dest: "/home/{{ SYS_USER }}/server/containers/crowdsec/config/profiles.yaml"

- name: Copy discord.yaml
  copy:
    src: discord.yaml
    dest: "/home/{{ SYS_USER }}/server/containers/crowdsec/config/notifications/discord.yaml"

- name: Create Dockerfile from template
  template:
    src: Dockerfile.j2
    dest: "/home/{{ SYS_USER }}/server/containers/crowdsec/Dockerfile"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_role:
    name: common
    tasks_from: docker_deploy.yml

- name: Ensure Crowdsec hub update and upgrade job exists
  ansible.builtin.cron:
    name: "Update Crowdsec Hub"   # Unique ID Ansible uses to track this specific line
    minute: "15"
    hour: "7"
    job: "docker exec crowdsec cscli hub update && docker exec crowdsec cscli hub upgrade"
    user: root
    state: present
