---
- name: Create required directories
  ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    common_dirs_to_create:
      - "{{ container_item.name }}"

- name: Create Dockerfile from template
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "/home/{{ sys_user }}/server/containers/crowdsec/Dockerfile"
    mode: "0664"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml

- name: Schedule weekly crowdsec redeploy cron job
  ansible.builtin.cron:
    name: "Redeploy crowdsec"
    weekday: "0"
    hour: "6"
    minute: "10"
    user: "{{ sys_user }}"
    job: "cd /home/{{ sys_user }}/server && ansible-playbook ansible/deploy.yml --tags crowdsec"
    state: present
