"""``docs/facts.lock``: the recorded hashes for every verified CLAUDE.md section.

Same shape and same rule as ``uv.lock``: derived, committed, regenerated by a command,
never hand-edited. It carries a checksum of its own body so a hand edit is a finding rather
than a silent re-verification. The lock is what lets CI fail the PR that moved an atom —
CI has no memory directory and no timer, so the repo store's status has to be reproducible
from the tree plus this file alone.
"""

import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from .atoms import HASHED_FORMS, Ambiguous, backrefs, hash_atom
from .citations import (
    Citation,
    in_tree,
    parse_citations,
    repo_docs,
    sections,
    tracked_files,
)
from .relations import Edb

LOCK_REL = "docs/facts.lock"
FINDING_KINDS = frozenset(
    {
        "moved",
        "missing",
        "section-gone",
        "atom-no-longer-cited",
        "unrecorded-atom",
        "interpreter-moved",
        "lock-tampered",
        "ambiguous",
    }
)
_PYTHON = f"{sys.version_info.major}.{sys.version_info.minor}"
_HEADER = "# Generated by `scripts/dev/fact_status.py verify`. Do not edit: the checksum below is over `units`.\n"


@dataclass(frozen=True)
class Finding:
    unit: str
    atom: str
    kind: str
    detail: str

    def __post_init__(self) -> None:
        # The census test asserts FINDING_KINDS holds what it holds; this asserts the
        # producers use it. Without it a kind added at a call site and left out of the
        # frozenset passes both, and `fact_status.py` prints a kind nothing documents.
        if self.kind not in FINDING_KINDS:
            raise ValueError(f"{self.kind!r} is not in FINDING_KINDS")


def _checksum(units: dict) -> str:
    return hashlib.sha256(json.dumps(units, sort_keys=True).encode()).hexdigest()


def read_lock(path: Path) -> dict[str, dict]:
    """The lock's ``units`` mapping, or ``{}`` when the file is absent or holds no body.

    Comment lines are stripped before the JSON is parsed: the header names the generator, and
    a reader who opens the file is the person most likely to hand-edit it.
    """
    if not path.is_file():
        return {}
    body = "\n".join(
        ln
        for ln in path.read_text(encoding="utf-8").splitlines()
        if not ln.startswith("#")
    )
    return json.loads(body)["units"] if body.strip() else {}


def write_lock(path: Path, units: dict[str, dict]) -> None:
    """Write ``units`` with a checksum over them, sorted so a diff shows only what changed.

    The one write path. Every caller that changes a row goes through it, which is what keeps
    the checksum a signal that a HUMAN edited the file rather than noise from the tool.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {"checksum": _checksum(units), "units": units}
    path.write_text(
        _HEADER + json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def lock_tampered(path: Path) -> bool:
    """Whether the lock's recorded checksum disagrees with its own units.

    False for an absent file: nothing to tamper with. A hand edit that changes a hash to
    silence a finding lands here rather than passing as a re-verification.
    """
    if not path.is_file():
        return False
    body = "\n".join(
        ln
        for ln in path.read_text(encoding="utf-8").splitlines()
        if not ln.startswith("#")
    )
    doc = json.loads(body)
    return doc.get("checksum") != _checksum(doc.get("units", {}))


Citations = dict[str, list[Citation]]
"""Every section's in-tree citations keyed by unit — one parse of the docs, shared by the readers below."""


def repo_citations(repo: Path) -> Citations:
    """Every section's IN-TREE citations, keyed by unit.

    The tracked set is read once per call: an out-of-tree span (``origin/master``, an
    untracked or gitignored file) parses as a path citation but is not support, so it never
    reaches the lock and never grades a section.

    Every reader below takes the result as an optional ``by_unit`` and parses for itself
    when it is not given: ``fact_status.py status`` calls two of them and lists the units,
    so passing one parse through is what keeps it from reading every document three times.
    """
    tracked = tracked_files(repo)
    out: dict[str, list[Citation]] = {}
    for doc in repo_docs(repo):
        rel = doc.relative_to(repo).as_posix()
        for sec in sections(rel, doc.read_text(encoding="utf-8")):
            cites, _ = parse_citations(sec.body)
            out[sec.key] = [c for c in cites if in_tree(c, tracked)]
    return out


def build_repo_edb(
    repo: Path, lock: dict[str, dict], by_unit: Citations | None = None
) -> Edb:
    """The repo store's ``Edb``: the tree supplies the citations and current hashes, ``lock`` the recorded ones.

    Every probe atom is put in both ``live`` and ``transport_failed``, because nothing here
    runs one — slice 5's reconcile timer supplies the shape. The effect is that a probe
    citation reads UNKNOWN rather than dragging its section OUT. ``memory_units`` and
    ``links`` stay empty until slice 4 adds the memory store.
    """
    if by_unit is None:
        by_unit = repo_citations(repo)
    cites: set[tuple[str, str]] = set()
    current: dict[str, str] = {}
    live: set[str] = set()
    failed: set[str] = set()
    backref: set[tuple[str, str]] = set()
    test_atoms: set[str] = set()
    for unit, cs in by_unit.items():
        for c in cs:
            cites.add((unit, c.raw))
            if c.form == "probe":
                live.add(c.raw)
                failed.add(
                    c.raw
                )  # never run here; slice 5's reconcile supplies the shape
                continue
            if c.form == "test":
                test_atoms.add(c.raw)
                backref.update((c.raw, u) for u in backrefs(c, repo))
            try:
                h = hash_atom(c, repo)
            except Ambiguous:
                h = None
            if h is not None:
                current[c.raw] = h
    recorded = {
        (u, a): h for u, rec in lock.items() for a, h in rec.get("atoms", {}).items()
    }
    return Edb(
        cites=frozenset(cites),
        recorded=recorded,
        current=current,
        live=frozenset(live),
        transport_failed=frozenset(failed),
        backref=frozenset(backref),
        links=frozenset(),
        memory_units=frozenset(),
        test_atoms=frozenset(test_atoms),
    )


def check_lock(
    repo: Path, lock_path: Path, by_unit: Citations | None = None
) -> list[Finding]:
    """Findings for every recorded atom that no longer hashes as recorded, is gone, or is no longer cited."""
    if lock_tampered(lock_path):
        return [
            Finding(
                "",
                "",
                "lock-tampered",
                f"{lock_path.name} checksum does not match its units; regenerate with `fact_status.py verify`",
            )
        ]
    lock = read_lock(lock_path)
    if by_unit is None:
        by_unit = repo_citations(repo)
    findings: list[Finding] = []
    for unit, rec in sorted(lock.items()):
        if unit not in by_unit:
            findings.append(
                Finding(
                    unit,
                    "",
                    "section-gone",
                    "no section with this heading; re-verify under the new heading with `fact_status.py verify`, then drop this row with `fact_status.py forget`",
                )
            )
            continue
        # An atom hash is only comparable against the interpreter that produced it: a symbol
        # and a test are hashed through `ast.unparse`, whose rendering is a property of the
        # running CPython. Report the move and skip the comparison rather than grade every
        # atom in the unit OUT for an upgrade that changed nothing about the code. A row with
        # no recorded version recorded nothing, so nothing moved.
        # DECIDED: this skips the whole unit, not only the hash comparison. `unrecorded-atom`
        # would still be valid here — set membership does not depend on the interpreter — but
        # its remedy is the same `verify` run, and one actionable finding beats several.
        recorded_python = rec.get("python")
        if recorded_python is not None and recorded_python != _PYTHON:
            findings.append(
                Finding(
                    unit,
                    "",
                    "interpreter-moved",
                    f"recorded under Python {recorded_python}, running {_PYTHON}; re-verify",
                )
            )
            continue
        cited = {c.raw: c for c in by_unit[unit]}
        for atom, recorded_hash in sorted(rec.get("atoms", {}).items()):
            if atom not in cited:
                findings.append(
                    Finding(
                        unit,
                        atom,
                        "atom-no-longer-cited",
                        "the section no longer cites it; re-run `fact_status.py verify` on the section",
                    )
                )
                continue
            try:
                now = hash_atom(cited[atom], repo)
            except Ambiguous:
                findings.append(
                    Finding(
                        unit,
                        atom,
                        "ambiguous",
                        "marker prefix matches more than one line; cite a longer prefix",
                    )
                )
                continue
            if now is None:
                findings.append(
                    Finding(unit, atom, "missing", "the atom no longer resolves")
                )
            elif now != recorded_hash:
                findings.append(
                    Finding(
                        unit,
                        atom,
                        "moved",
                        f"recorded {recorded_hash[:8]}, now {now[:8]}",
                    )
                )
        # A citation ADDED to an already-verified section. `status` grades the unit OUT for
        # it (relations.unrecorded), but until now nothing in CI did: the guard walked the
        # recorded atoms alone, so a new fact could be added to a locked section and land
        # unsupported behind a green master.
        recorded_atoms = rec.get("atoms", {})
        for atom, c in sorted(cited.items()):
            if atom in recorded_atoms or c.form not in HASHED_FORMS:
                continue
            findings.append(
                Finding(
                    unit,
                    atom,
                    "unrecorded-atom",
                    "the section cites it and the lock has no hash for it; re-run `fact_status.py verify` on the section, or fix the citation if verify reports it skipped",
                )
            )
    return findings


def verify_units(
    repo: Path,
    lock_path: Path,
    unit_keys: list[str],
    head_sha: str,
    by_unit: Citations | None = None,
) -> tuple[dict[str, dict], list[str]]:
    """Re-hash every hashable atom the named sections cite, write the lock, and name what it skipped.

    Returns the whole lock and the sorted citations that did NOT resolve, so the caller can
    say so: a section can otherwise read `verified` while the atom the author cared about
    was silently dropped. Raises ``KeyError`` on an unknown unit.
    """
    if by_unit is None:
        by_unit = repo_citations(repo)
    lock = read_lock(lock_path)
    skipped: set[str] = set()
    for key in unit_keys:
        atoms: dict[str, str] = {}
        for c in by_unit[key]:
            h = hash_atom(c, repo)
            if h is not None:
                atoms[c.raw] = h
            elif c.form in HASHED_FORMS:
                skipped.add(c.raw)
        lock[key] = {"verified_sha": head_sha, "python": _PYTHON, "atoms": atoms}
    write_lock(lock_path, lock)
    return lock, sorted(skipped)


def forget_units(lock_path: Path, keys: list[str]) -> dict[str, dict]:
    """Drop the named rows and rewrite the lock. Raises ``KeyError`` on a key with no row.

    The way out of a `section-gone` finding. Renaming a heading makes a new unit and strands
    the old row, and hand-editing the lock is what its checksum exists to catch — so the tool
    has to own the deletion as well as the write.
    """
    lock = read_lock(lock_path)
    for key in keys:
        del lock[key]
    write_lock(lock_path, lock)
    return lock
