"""``docs/facts.lock``: the recorded hashes for every verified CLAUDE.md section.

Same shape and same rule as ``uv.lock``: derived, committed, regenerated by a command,
never hand-edited. It carries a checksum of its own body so a hand edit is a finding rather
than a silent re-verification. The lock is what lets CI fail the PR that moved an atom —
CI has no memory directory and no timer, so the repo store's status has to be reproducible
from the tree plus this file alone.
"""

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from .atoms import Ambiguous, backrefs, hash_atom
from .citations import (
    Citation,
    in_tree,
    parse_citations,
    repo_docs,
    sections,
    top_level_dirs,
)
from .relations import Edb

LOCK_REL = "docs/facts.lock"
FINDING_KINDS = frozenset(
    {
        "moved",
        "missing",
        "section-gone",
        "atom-no-longer-cited",
        "lock-tampered",
        "ambiguous",
    }
)
_HEADER = "# Generated by `scripts/dev/fact_status.py verify`. Do not edit: the checksum below is over `units`.\n"


@dataclass(frozen=True)
class Finding:
    unit: str
    atom: str
    kind: str
    detail: str


def _checksum(units: dict) -> str:
    return hashlib.sha256(json.dumps(units, sort_keys=True).encode()).hexdigest()


def read_lock(path: Path) -> dict[str, dict]:
    if not path.is_file():
        return {}
    body = "\n".join(
        ln for ln in path.read_text().splitlines() if not ln.startswith("#")
    )
    return json.loads(body)["units"] if body.strip() else {}


def write_lock(path: Path, units: dict[str, dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {"checksum": _checksum(units), "units": units}
    path.write_text(
        _HEADER + json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    )


def lock_tampered(path: Path) -> bool:
    if not path.is_file():
        return False
    body = "\n".join(
        ln for ln in path.read_text().splitlines() if not ln.startswith("#")
    )
    doc = json.loads(body)
    return doc.get("checksum") != _checksum(doc.get("units", {}))


def _repo_citations(repo: Path) -> dict[str, list[Citation]]:
    """Every section's IN-TREE citations, keyed by unit.

    The roots are read once per call: an out-of-tree span (``origin/master``, a doc-relative
    ``defaults/main.yml``) parses as a path citation but is not support, so it never reaches
    the lock and never grades a section.
    """
    roots = top_level_dirs(repo)
    out: dict[str, list[Citation]] = {}
    for doc in repo_docs(repo):
        rel = doc.relative_to(repo).as_posix()
        for sec in sections(rel, doc.read_text(encoding="utf-8")):
            cites, _ = parse_citations(sec.body)
            out[sec.key] = [c for c in cites if in_tree(c, roots)]
    return out


def build_repo_edb(repo: Path, lock: dict[str, dict]) -> Edb:
    by_unit = _repo_citations(repo)
    cites: set[tuple[str, str]] = set()
    current: dict[str, str] = {}
    live: set[str] = set()
    failed: set[str] = set()
    backref: set[tuple[str, str]] = set()
    test_atoms: set[str] = set()
    for unit, cs in by_unit.items():
        for c in cs:
            cites.add((unit, c.raw))
            if c.form == "probe":
                live.add(c.raw)
                failed.add(
                    c.raw
                )  # never run here; slice 5's reconcile supplies the shape
                continue
            if c.form == "test":
                test_atoms.add(c.raw)
                backref.update((c.raw, u) for u in backrefs(c, repo))
            try:
                h = hash_atom(c, repo)
            except Ambiguous:
                h = None
            if h is not None:
                current[c.raw] = h
    recorded = {
        (u, a): h for u, rec in lock.items() for a, h in rec.get("atoms", {}).items()
    }
    return Edb(
        cites=frozenset(cites),
        recorded=recorded,
        current=current,
        live=frozenset(live),
        transport_failed=frozenset(failed),
        backref=frozenset(backref),
        links=frozenset(),
        memory_units=frozenset(),
        test_atoms=frozenset(test_atoms),
    )


def check_lock(repo: Path, lock_path: Path) -> list[Finding]:
    """Findings for every recorded atom that no longer hashes as recorded, is gone, or is no longer cited."""
    if lock_tampered(lock_path):
        return [
            Finding(
                "",
                "",
                "lock-tampered",
                f"{lock_path.name} checksum does not match its units; regenerate with `fact_status.py verify`",
            )
        ]
    lock = read_lock(lock_path)
    by_unit = _repo_citations(repo)
    findings: list[Finding] = []
    for unit, rec in sorted(lock.items()):
        if unit not in by_unit:
            findings.append(
                Finding(
                    unit,
                    "",
                    "section-gone",
                    "no section with this heading; rename the lock row with `fact_status.py verify` or delete it",
                )
            )
            continue
        cited = {c.raw: c for c in by_unit[unit]}
        for atom, recorded_hash in sorted(rec.get("atoms", {}).items()):
            if atom not in cited:
                findings.append(
                    Finding(
                        unit,
                        atom,
                        "atom-no-longer-cited",
                        "the section no longer cites it; re-run `fact_status.py verify` on the section",
                    )
                )
                continue
            try:
                now = hash_atom(cited[atom], repo)
            except Ambiguous:
                findings.append(
                    Finding(
                        unit,
                        atom,
                        "ambiguous",
                        "marker prefix matches more than one line; cite a longer prefix",
                    )
                )
                continue
            if now is None:
                findings.append(
                    Finding(unit, atom, "missing", "the atom no longer resolves")
                )
            elif now != recorded_hash:
                findings.append(
                    Finding(
                        unit,
                        atom,
                        "moved",
                        f"recorded {recorded_hash[:8]}, now {now[:8]}",
                    )
                )
    return findings


def verify_units(
    repo: Path, lock_path: Path, unit_keys: list[str], head_sha: str
) -> dict[str, dict]:
    """Re-hash every hashable atom the named sections cite and write the lock. Raises ``KeyError`` on an unknown unit."""
    by_unit = _repo_citations(repo)
    lock = read_lock(lock_path)
    for key in unit_keys:
        atoms: dict[str, str] = {}
        for c in by_unit[key]:
            h = hash_atom(c, repo)
            if h is not None:
                atoms[c.raw] = h
        lock[key] = {"verified_sha": head_sha, "atoms": atoms}
    write_lock(lock_path, lock)
    return lock
