# Use the official n8n image as the base
FROM n8nio/n8n:latest

# Switch to the root user to install packages
USER root

# Force npm to use /usr/local
ENV NPM_CONFIG_PREFIX=/usr/local

# Add your npm packages here.
# Use 'RUN npm install -g ...'
# Example:
RUN npm install -g fuzzball

# Switch back to the non-privileged 'node' user
USER node
