- name: Creates directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/homeassistant/config"
    state: directory
    mode: 0755

- name: Create configuration.yaml from template
  template:
    src: configuration.yaml.j2
    dest: "/home/{{ env.SYS_USER }}/server/homeassistant/config/configuration.yaml"

- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ env.SYS_USER }}/server/homeassistant/docker-compose.yml"
    
- name: Deploy Home Assistant
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/homeassistant/"
  become: yes
  become_method: sudo