---
- name: Create required directories
  ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    common_dirs_to_create:
      - "{{ container_item.name }}/config/wg_confs"
      - "data/downloads"

- name: Copy wg0.conf
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "/home/{{ sys_user }}/server/containers/{{ role_name }}/config/wg_confs/wg0.conf"
    mode: "0755"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml

- name: Add Systemd Service
  ansible.builtin.template:
    src: docker-compose.app.service.j2
    dest: /etc/systemd/system/docker-compose-{{ role_name }}.service
    mode: "0644"
  become: true

- name: Ensure Systemd Service is enabled and started
  ansible.builtin.systemd:
    name: docker-compose-{{ role_name }}.service
    enabled: true
    state: started
    daemon_reload: true
  become: true
