#!/usr/bin/env python3
"""Generate the fact tables the hand-written docs transclude.

WHY FRAGMENTS. The reference pages under docs/reference/ are generated whole, so a tunable
they show is re-read from the tree on every docs-refresh run. The operations pages are
prose, and prose quotes the same tunables: a retain count, the broad-prefix classes, the
staging subset. Nothing regenerated those, and on 2026-09-02 five such figures were stale.
Moving a whole runbook into a generator would put its prose in Python; leaving it alone
leaves the tables to rot. A fragment is the seam between the two: the generator emits ONLY
the table, and the page pulls it in with a `pymdownx.snippets` include::

    --8<-- "assets/generated/fragments/longhorn-tiers.md"

The prose around it stays hand-written. mkdocs.yml enables the extension with
`check_paths: true`, so an include naming a fragment that does not exist fails the strict
build rather than rendering the include line as text.

WHAT A FRAGMENT CARRIES. No frontmatter -- a snippet is spliced into the page verbatim, so
a `---` block would render as a rule and three lines of text. The provenance is an HTML
comment on the first line, and it carries the literal `generated_from:` because that string
is how .claude/hooks/block-protected-edits.py tells a generated page from a hand-written
one. No timestamp either: docs_provenance.write_if_body_changed compares the whole file
when there is no frontmatter, and a stamp would make every run a rewrite and every cron
run a commit. When a fragment's content last changed is its git history.

STATIC PARSING ONLY, like every generator here. Role defaults are read with yaml.safe_load
and Python constants with `ast`, never by importing the deployer or the rotation tool --
both bootstrap sys.path and read the environment on import.

Every fragment must be included by at least one page and every include must name a
fragment this script emits; scripts/docs/tests/test_gen_doc_fragments.py checks both
directions, so a fragment cannot go dead and a page cannot include a name nobody writes.

Usage::

    uv run python scripts/docs/gen_doc_fragments.py --out-dir docs/assets/generated/fragments
"""

from __future__ import annotations

import argparse
import ast
import configparser
import sys as _sys
from collections.abc import Callable
from pathlib import Path as _Path

import yaml

# Reach the sibling package directories: a directly-invoked script gets only its own
# directory on sys.path, and pyproject's `pythonpath` is a pytest setting.
_sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))

from lib.docs_provenance import write_if_body_changed
from lib.repo_paths import REPO

SELF = "scripts/docs/gen_doc_fragments.py"
DEFAULT_OUT_DIR = "docs/assets/generated/fragments"

K3S_DEFAULTS = REPO / "ansible/roles/setup/k3s/defaults/main.yml"
GITOPS_DEFAULTS = REPO / "ansible/roles/setup/gitops_deploy/defaults/main.yml"
DEPLOY_CHANGES = REPO / "ansible/roles/setup/gitops_deploy/files/deploy_changes.py"
GITOPS_DEPLOY = REPO / "ansible/roles/setup/gitops_deploy/files/gitops_deploy.py"
SECRET_ROTATION = REPO / "scripts/secrets_mgmt/secret_rotation.py"
SECRET_REGISTRY = REPO / "ansible/secret_rotation.yml"
PI_PEER_DEFAULTS = REPO / "ansible/roles/k8s/pi-peer-backup/defaults/main.yml"
REGISTRY_DEFAULTS = REPO / "ansible/roles/k8s/registry/defaults/main.yml"
FAIL2BAN_CONF = (
    REPO / "ansible/roles/setup/initial_setup/templates/fail2ban_homelab.conf.j2"
)
GROUP_VARS = REPO / "ansible/inventory/group_vars/all.yml"
HOST_VARS = REPO / "ansible/inventory/host_vars"


def header(sources: list[str]) -> str:
    """The first line of every fragment: provenance the hook can read, in a comment."""
    return (
        f"<!-- generated_from: {SELF} -- do not edit. Regenerated by the docs-refresh cron "
        f"from {', '.join(sources)}; change the source. -->\n"
    )


# --- readers -----------------------------------------------------------------------------


def module_constant(path: _Path, name: str):
    """The literal a module assigns to `name` at top level, without importing the module."""
    tree = ast.parse(path.read_text())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == name for t in node.targets
        ):
            return ast.literal_eval(node.value)
    raise KeyError(f"{path.relative_to(REPO)}: no top-level `{name} = <literal>`")


def config_default(path: _Path, name: str) -> str:
    """The default string a `C.get("<name>", "<default>")` call supplies for `name`.

    The deployer reads its tunables from a config file with a literal fallback. The
    fallback is what the tree says; a host's config.env can override it, and a fragment
    says so where it matters.
    """
    for node in ast.walk(ast.parse(path.read_text())):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "get"
            and len(node.args) == 2
            and isinstance(node.args[0], ast.Constant)
            and node.args[0].value == name
            and isinstance(node.args[1], ast.Constant)
        ):
            return str(node.args[1].value)
    raise KeyError(f"{path.relative_to(REPO)}: no `C.get({name!r}, <default>)` call")


def role_defaults(path: _Path) -> dict:
    return yaml.safe_load(path.read_text())


def registry_counts(path: _Path) -> dict[str, int]:
    """How many registered secrets sit in each tier."""
    counts: dict[str, int] = {}
    for entry in yaml.safe_load(path.read_text())["secrets"].values():
        tier = str(entry.get("tier", "?"))
        counts[tier] = counts.get(tier, 0) + 1
    return counts


# --- renderers: pure functions of what the readers return --------------------------------


def _code_list(items: list[str]) -> str:
    return ", ".join(f"`{item}`" for item in items)


def render_longhorn_tiers(d: dict) -> str:
    """Renders the Longhorn backup-tier markdown table fragment.

    Args:
        d: the k3s role's defaults, carrying the longhorn tier and schedule tunables.
    """
    r2 = list(d["k3s_longhorn_r2_volumes"])
    weekly = list(d["k3s_longhorn_weekly_volumes"])
    nobackup = list(d["k3s_longhorn_nobackup_volumes"])
    minute, hour = str(d["k3s_longhorn_weekly_backup_minute_hour"]).split()
    armed = "armed" if d["k3s_longhorn_backup_armed"] else "**disarmed**"
    lines = [
        "| Tier | Target | Volumes | Schedule (daniel-box, UTC) | Retain |",
        "|---|---|---|---|---|",
        f"| Daily | R2 (`r2`) | {len(r2)} | `{d['k3s_longhorn_backup_cron']}` "
        f"| {d['k3s_longhorn_backup_retain']} |",
        f"| Weekly | B2 (`default`) | {len(weekly)}, one weekday each "
        f"| `{minute} {hour} * * <index mod 7>` | {d['k3s_longhorn_weekly_backup_retain']} |",
        f"| None | — | {len(nobackup)} listed, plus the `longhorn-nobackup` StorageClass | — | — |",
        "",
        f"Daily-tier volumes (`k3s_longhorn_r2_volumes`): {_code_list(r2)}.",
        "",
        f"B2 backups are {armed} (`k3s_longhorn_backup_armed`); the daily B2 budget is "
        f"{d['k3s_longhorn_daily_backup_budget']} backups (`k3s_longhorn_daily_backup_budget`).",
    ]
    return "\n".join(lines) + "\n"


def render_gitops_prefixes(setup: tuple, deploy: tuple, manual: tuple) -> str:
    """Renders the GitOps broad-change prefix classification table fragment.

    Args:
        setup: prefixes the deployer fast-forwards then applies via `initial_setup.yml`.
        deploy: prefixes the deployer fast-forwards then applies via a full `deploy.yml`.
        manual: prefixes the deployer never applies automatically.
    """
    rows = [
        ("Setup, scoped", setup, "_BROAD_SETUP_PREFIXES",
         "fast-forwards, then runs `initial_setup.yml --tags <name>`"),
        ("Deploy plane", deploy, "_BROAD_DEPLOY_PREFIXES",
         "fast-forwards, then runs a full `ansible/deploy.yml`"),
        ("Never applied here", manual, "_BROAD_MANUAL_PREFIXES",
         "alerts and returns **without fast-forwarding**"),
    ]  # fmt: skip
    lines = ["| Class | Prefixes | What the deployer does |", "|---|---|---|"]
    for label, prefixes, constant, action in rows:
        lines.append(
            f"| {label} | {_code_list(list(prefixes))} (`{constant}`) | {action} |"
        )
    return "\n".join(lines) + "\n"


def render_staging_subset(csv: str) -> str:
    names = sorted(n.strip() for n in csv.split(",") if n.strip())
    return (
        f"The subset as the deployer defaults it (`STAGING_SUBSET` in `gitops_deploy.py`; a "
        f"host's `config.env` can override it): {_code_list(names)} — {len(names)} services.\n"
    )


def render_secret_tiers(tier_days: dict, lead_days: int, counts: dict[str, int]) -> str:
    """Renders the secret-rotation tier table fragment.

    Args:
        tier_days: tier name to rotation cadence in days, or None for no cadence.
        lead_days: `ROTATE_LEAD_DAYS`, the window the weekly auto rotation takes.
        counts: tier name to registered secret count.
    """
    lines = ["| Tier | Cadence | Registered |", "|---|---|---|"]
    for tier, days in tier_days.items():
        cadence = f"{days} d" if days is not None else "—"
        lines.append(f"| `{tier}` | {cadence} | {counts.get(tier, 0)} |")
    total = sum(counts.values())
    lines += [
        "",
        f"{total} secrets are registered. The weekly `auto` rotation takes anything due within "
        f"`ROTATE_LEAD_DAYS` = {lead_days} days.",
    ]
    return "\n".join(lines) + "\n"


# --- the fragment set --------------------------------------------------------------------


def _longhorn() -> tuple[str, list[str]]:
    return render_longhorn_tiers(role_defaults(K3S_DEFAULTS)), [
        "ansible/roles/setup/k3s/defaults/main.yml"
    ]


def _gitops() -> tuple[str, list[str]]:
    return render_gitops_prefixes(
        module_constant(DEPLOY_CHANGES, "_BROAD_SETUP_PREFIXES"),
        module_constant(DEPLOY_CHANGES, "_BROAD_DEPLOY_PREFIXES"),
        module_constant(DEPLOY_CHANGES, "_BROAD_MANUAL_PREFIXES"),
    ), ["ansible/roles/setup/gitops_deploy/files/deploy_changes.py"]


def _staging() -> tuple[str, list[str]]:
    return render_staging_subset(config_default(GITOPS_DEPLOY, "STAGING_SUBSET")), [
        "ansible/roles/setup/gitops_deploy/files/gitops_deploy.py"
    ]


def parse_jails(conf: str) -> list[dict[str, str]]:
    """Every enabled jail with its effective maxretry, findtime and bantime.

    The template is plain INI, so configparser reads it and resolves each jail's values
    through `[DEFAULT]` the way fail2ban does.
    """
    parser = configparser.ConfigParser(interpolation=None)
    parser.read_string(conf)
    jails = []
    for name in parser.sections():
        section = parser[name]
        if section.get("enabled", "false").lower() != "true":
            continue
        jails.append(
            {
                "jail": name,
                "maxretry": section["maxretry"],
                "findtime": section["findtime"],
                "bantime": section["bantime"],
            }
        )
    return jails


def container_udp_port(host_vars: dict, name: str) -> str:
    entries = [c for c in host_vars["containers_list"] if c.get("name") == name]
    assert len(entries) == 1, (
        f"expected one {name!r} in containers_list, found {len(entries)}"
    )
    return str(entries[0]["udp_port"])


def render_deadman_cadences(k3s: dict, pi_peer: dict, registry: dict) -> str:
    """One row per Healthchecks.io slug: the cron that pings it, assembled from its vars."""
    every_10 = f"{k3s['k3s_longhorn_backup_health_cron_minute']} * * * *"
    rows = [
        (
            "longhorn-backup-health",
            every_10,
            "`k3s_longhorn_backup_health_cron_minute`",
        ),
        (
            "daniel-box-disk-health",
            f"{k3s['k3s_disk_health_cron_minute']} * * * *",
            "`k3s_disk_health_cron_minute`",
        ),
        (
            "etcd-snapshot-offbox",
            f"{k3s['k3s_etcd_s3_cron_minute']} {k3s['k3s_etcd_s3_cron_hour']} * * *",
            "`k3s_etcd_s3_cron_hour` / `_minute`",
        ),
        (
            "manifest-prune-check",
            f"{k3s['k3s_manifest_prune_cron_minute']} {k3s['k3s_manifest_prune_cron_hour']} * * *",
            "`k3s_manifest_prune_cron_hour` / `_minute`",
        ),
        (
            "pi-peer-backup",
            str(pi_peer["pi_peer_backup_k8s_schedule"]),
            "`pi_peer_backup_k8s_schedule` (a k8s CronJob, not a host cron)",
        ),
        (
            "registry-gc",
            f"{registry['registry_k8s_gc_cron_minute']} {registry['registry_k8s_gc_cron_hour']} "
            f"* * {registry['registry_k8s_gc_cron_weekday']}",
            "`registry_k8s_gc_cron_weekday` / `_hour` / `_minute`",
        ),
        (
            "uptime-kuma-alive",
            every_10,
            "the `longhorn-backup-health` cron; the same script pings both",
        ),
    ]
    lines = ["| Check slug | Cron (daniel-box, UTC) | Set by |", "|---|---|---|"]
    lines += [f"| `{slug}` | `{cron}` | {source} |" for slug, cron, source in rows]
    return "\n".join(lines) + "\n"


def render_fail2ban_jails(jails: list[dict[str, str]]) -> str:
    lines = ["| Jail | Trigger | Ban |", "|---|---|---|"]
    for j in jails:
        lines.append(
            f"| `{j['jail']}` | {j['maxretry']} failures in {j['findtime']} "
            f"(`maxretry {j['maxretry']}`, `findtime {j['findtime']}`) | {j['bantime']} |"
        )
    return "\n".join(lines) + "\n"


def render_lan_addresses(
    ingress_vip: str, dns_vip: str, wg_port: str, pi_wg_port: str
) -> str:
    """Renders the LAN address table fragment.

    Args:
        ingress_vip: the k3s MetalLB ingress VIP every `.local` service answers on.
        dns_vip: the Pi-hole DNS MetalLB VIP.
        wg_port: the WireGuard UDP port for wg-easy on daniel-box.
        pi_wg_port: the WireGuard UDP port for the Pi's LAN-only wg-easy.
    """
    rows = [
        ("k3s ingress VIP (MetalLB; every `.local` service answers here)", ingress_vip,
         "`k3s_metallb_ingress_vip`"),
        ("Pi-hole DNS VIP (MetalLB)", dns_vip, "`dns_k8s_vip`"),
        ("WireGuard UDP port, wg-easy on daniel-box", f"{wg_port}/udp",
         "`udp_port` on the k8s `wg-easy` entry in `host_vars/daniel-box.yml`"),
        ("WireGuard UDP port, the Pi's LAN-only wg-easy", f"{pi_wg_port}/udp",
         "`udp_port` on `wg-easy` in `host_vars/daniel-pi.yml`"),
    ]  # fmt: skip
    lines = ["| Address | Value | Set by |", "|---|---|---|"]
    lines += [f"| {what} | `{value}` | {source} |" for what, value, source in rows]
    return "\n".join(lines) + "\n"


def _deadman() -> tuple[str, list[str]]:
    return render_deadman_cadences(
        role_defaults(K3S_DEFAULTS),
        role_defaults(PI_PEER_DEFAULTS),
        role_defaults(REGISTRY_DEFAULTS),
    ), [
        "ansible/roles/setup/k3s/defaults/main.yml",
        "ansible/roles/k8s/pi-peer-backup/defaults/main.yml",
        "ansible/roles/k8s/registry/defaults/main.yml",
    ]


def _fail2ban() -> tuple[str, list[str]]:
    return render_fail2ban_jails(parse_jails(FAIL2BAN_CONF.read_text())), [
        "ansible/roles/setup/initial_setup/templates/fail2ban_homelab.conf.j2"
    ]


def _lan() -> tuple[str, list[str]]:
    group = role_defaults(GROUP_VARS)
    return render_lan_addresses(
        str(group["k3s_metallb_ingress_vip"]),
        str(group["dns_k8s_vip"]),
        container_udp_port(role_defaults(HOST_VARS / "daniel-box.yml"), "wg-easy"),
        container_udp_port(role_defaults(HOST_VARS / "daniel-pi.yml"), "wg-easy"),
    ), [
        "ansible/inventory/group_vars/all.yml",
        "ansible/inventory/host_vars/daniel-box.yml",
        "ansible/inventory/host_vars/daniel-pi.yml",
    ]


def _secrets() -> tuple[str, list[str]]:
    return render_secret_tiers(
        module_constant(SECRET_ROTATION, "TIER_DAYS"),
        module_constant(SECRET_ROTATION, "ROTATE_LEAD_DAYS"),
        registry_counts(SECRET_REGISTRY),
    ), ["scripts/secrets_mgmt/secret_rotation.py", "ansible/secret_rotation.yml"]


# name -> () -> (body, sources). The name is the file stem a page includes.
FRAGMENTS: dict[str, Callable[[], tuple[str, list[str]]]] = {
    "longhorn-tiers": _longhorn,
    "broad-prefixes": _gitops,
    "staging-subset": _staging,
    "secret-tiers": _secrets,
    "deadman-cadences": _deadman,
    "fail2ban-jails": _fail2ban,
    "lan-addresses": _lan,
}


def write_fragments(out_dir: _Path) -> int:
    """Write every fragment whose content changed. Returns how many were written."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    for name, build in FRAGMENTS.items():
        body, sources = build()
        if write_if_body_changed(out_dir / f"{name}.md", header(sources) + body):
            written += 1
    return written


def main(argv: list[str] | None = None) -> int:
    """Entry point: writes every fragment and prints how many changed.

    Args:
        argv: command-line arguments, or None to use `sys.argv`.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out-dir", default=DEFAULT_OUT_DIR, help="where the fragments go"
    )
    args = parser.parse_args(argv)
    out_dir = _Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = REPO / out_dir
    written = write_fragments(out_dir)
    print(
        f"gen_doc_fragments: {len(FRAGMENTS)} fragment(s), {written} written -> {out_dir}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
