- name: Creates directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/mobile-app-db/config"
    state: directory
    mode: 0755

- name: Create Dockerfile from template
  template:
    src: /project_tracker_server/Dockerfile.j2
    dest: "/home/{{ env.SYS_USER }}/server/mobile-app-db/Dockerfile"

- name: Create docker-compose.yml from template
  template:
    src: /project_tracker_server/docker-compose.yml.j2
    dest: "/home/{{ env.SYS_USER }}/server/mobile-app-db/docker-compose.yml"

- name: Deploy mobile-app-db
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/mobile-app-db/"
  become: yes
  become_method: sudo