- name: Creates directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/mobile-app-db"
    state: directory
    mode: 0755

- name: Copy zip
  template:
    src: project_tracker_server.zip
    dest: "/home/{{ env.SYS_USER }}/server/mobile-app-db/project_tracker_server.zip"

- name: Unzip file
  shell: unzip project_tracker_server.zip
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/mobile-app-db/"
  become: yes
  become_method: sudo

- name: Deploy mobile-app-db
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/mobile-app-db/project_tracker_server"
  become: yes
  become_method: sudo