#!/usr/bin/env python3
"""Tests for `_facts_line`, the facts.lock line inject-nested-docs puts under a CLAUDE.md.

Driven through the hook's `build_context` and `render`, because the line is only worth having
as the hook delivers it. The fixture is a real git repository: a citation is support only
when it names a tracked file, and `lib.facts.citations.tracked_files` asks `git ls-files`.

Run: uv run pytest .claude/hooks/tests/test_facts_line.py
"""

import json
import sys
import tempfile

import pytest
import test_inject_nested_docs as base

from lib.git_testing import git, init_repo

# Taken from the base module, which puts `.claude/hooks` on `sys.path` before importing it.
_mod = base._mod
INSTRUCTIONS_LOG_ENV = base.INSTRUCTIONS_LOG_ENV

ROLE = "ansible/roles/k8s/foo"
DOC = f"{ROLE}/CLAUDE.md"
COMMAND = f"cat {ROLE}/tasks/main.yml"

ROLE_DOC = f"""# foo

Intro prose that cites nothing.

## Layout

The tasks live in `{ROLE}/tasks/main.yml`.

## Traps

The template is `{ROLE}/templates/deployment.yaml.j2`.

## Habits

Prose that cites nothing, so the lock has nothing to check.
"""


def _write_lock(root, *headings):
    units = {f"{DOC}#{h}": {"atoms": {}, "python": "3.14"} for h in headings}
    body = json.dumps({"checksum": "unchecked-here", "units": units}, indent=2)
    (root / "docs" / "facts.lock").write_text(f"# Generated by a test.\n{body}\n")


@pytest.fixture
def repo(tmp_path, monkeypatch):
    """A tracked role doc with one verified, one unverified and one convention section."""
    root = init_repo(tmp_path / "repo")
    (root / ROLE / "tasks").mkdir(parents=True)
    (root / ROLE / "templates").mkdir()
    (root / "docs").mkdir()
    (root / "CLAUDE.md").write_text("# root\n")
    (root / DOC).write_text(ROLE_DOC)
    (root / ROLE / "tasks" / "main.yml").write_text("---\n")
    (root / ROLE / "templates" / "deployment.yaml.j2").write_text("kind: Deployment\n")
    _write_lock(root, "Layout")
    git(root, "add", "-A")
    monkeypatch.setattr(tempfile, "gettempdir", lambda: str(tmp_path))
    monkeypatch.setenv(INSTRUCTIONS_LOG_ENV, str(tmp_path / "instructions.log"))
    return root


def _facts_lines(context):
    return [ln for ln in context.splitlines() if ln.startswith("facts.lock:")]


def test_a_doc_with_an_unverified_section_names_only_that_section(repo):
    context, chosen = _mod.build_context(COMMAND, str(repo), "sess-a")
    assert [d for d, _ in chosen] == [DOC]
    assert _facts_lines(context) == ['facts.lock: not verified: "Traps"']


def test_a_fully_verified_doc_has_no_facts_line(repo):
    _write_lock(repo, "Layout", "Traps")
    context, chosen = _mod.build_context(COMMAND, str(repo), "sess-a")
    assert [d for d, _ in chosen] == [DOC]
    assert _facts_lines(context) == []


def test_a_doc_with_no_room_for_the_line_stays_whole_without_it(repo):
    """The doc's own text outranks the line, so `_doc_size.MAX_CHARS` still means a whole doc."""
    header = _mod._header(DOC, ROLE)
    budget = _mod.INLINE_MAX_CHARS - len(_mod._PREAMBLE)
    text = "# foo\n" + "x" * (budget - 100 - len(header) - 2 - len("# foo\n"))
    (repo / DOC).write_text(text)
    block = _mod.render(str(repo), DOC, ROLE, 10**6, 10**6, "L" * 300)
    assert block == f"{header}\n{text}\n"


def test_the_doc_is_injected_when_the_facts_library_cannot_be_imported(
    repo, monkeypatch
):
    """A broken `lib.facts` costs the line, never the injection it rides on."""
    monkeypatch.setitem(sys.modules, "lib.facts.citations", None)  # import raises
    context, chosen = _mod.build_context(COMMAND, str(repo), "sess-a")
    assert [d for d, _ in chosen] == [DOC]
    assert "The template is" in context
    assert _facts_lines(context) == []
