#!/usr/bin/env python3
"""Table-driven tests for the block-protected-edits PreToolUse guard.

The guard denies two classes of direct edit that are always a mistake here:
  1. anything under `containers/` — generated by Ansible, overwritten on deploy.
  2. a SOPS-encrypted file — editing ciphertext corrupts it / risks committing a
     plaintext secret; you must go through `sops`.

The SOPS check is CONTENT-based, not path-based: `host_vars/*.yml` and
`group_vars/all.yml` contain the substring "vars/" but are PLAINTEXT and must stay
editable, so the guard keys off the file's actual `ENC[AES256_GCM` markers.

Run: uv run pytest .claude/hooks
"""

import importlib.util
import os
import sys

_HOOK = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "block-protected-edits.py",
)
sys.path.insert(
    0, os.path.dirname(_HOOK)
)  # block-protected-edits.py imports _hook_common
_spec = importlib.util.spec_from_file_location("block_protected_edits", _HOOK)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
classify = _mod.classify
is_sops_encrypted = _mod.is_sops_encrypted
find_repo_root = _mod.find_repo_root

# Repo root derived from THIS file's location (.claude/hooks/tests/), NOT hardcoded — the test
# must work in any checkout, incl. CI's /home/runner/work/... A hardcoded /home/ubuntu/server made
# classify() read a nonexistent secrets.yml in CI -> None -> a false `test_blocks_the_real_secrets_file`
# failure. Mirrors the hook's own repo_root computation in block-protected-edits.py.
REPO = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)


BLOCK_CONTAINERS = [
    ("containers/jellyfin/docker-compose.yml", "relative path in containers"),
    (os.path.join(REPO, "containers/jellyfin/docker-compose.yml"), "absolute path"),
    ("containers", "the containers dir itself"),
    ("ansible/../containers/foo.yml", "path that normalizes into containers"),
]

ALLOW_NONCONTAINERS = [
    (
        "ansible/roles/containers/jellyfin/templates/docker-compose.yml.j2",
        "the template",
    ),
    ("scripts/diagnostics/probe.py", "a script"),
    ("CLAUDE.md", "repo root file"),
    ("containers-notes/readme.md", "sibling that only shares a prefix"),
]


def test_blocks_writes_under_containers():
    for path, label in BLOCK_CONTAINERS:
        assert classify(path, REPO) is not None, f"should BLOCK: {label} ({path!r})"


def test_allows_writes_elsewhere():
    for path, label in ALLOW_NONCONTAINERS:
        assert classify(path, REPO) is None, f"should ALLOW: {label} ({path!r})"


def test_containers_reason_points_at_template_dir():
    reason = classify("containers/jellyfin/docker-compose.yml", REPO)
    assert "ansible/roles/containers" in reason


# Fixtures are built by concatenation so a SOPS signature never appears as a
# contiguous string in THIS source file — otherwise the guard would block editing
# this very test. _ENC keeps "ENC[" + "AES256_GCM" split across the +; the encrypted
# fixture carries a `mac:` metadata line (the structural signal the guard keys off).
_ENC = "ENC[" + "AES256_GCM,data:Zz==,iv:Yy=,tag:Xx==,type:str]"
SOPS_TEXT = (
    "db_password: " + _ENC + "\n"
    "sops:\n"
    '    lastmodified: "2026-06-15T13:17:13Z"\n'
    "    mac: " + _ENC + "\n"
    "    version: 3.9.2\n"
)
PLAINTEXT_HOST_VARS = "server_ip: 10.0.0.161\ncontainers_list:\n  - name: jellyfin\n"
# A doc/log that merely *mentions* the marker in prose — must NOT be flagged. This is
# the iteration-3 regression: the bare-substring check wrongly blocked such files.
PROSE_MENTIONING_MARKER = (
    "Detection keys off the file's " + "ENC[" + "AES256_GCM markers.\n"
)


def test_is_sops_encrypted_true_on_real_sops_metadata():
    assert is_sops_encrypted(SOPS_TEXT) is True


def test_is_sops_encrypted_false_on_plaintext():
    assert is_sops_encrypted(PLAINTEXT_HOST_VARS) is False
    assert is_sops_encrypted("") is False


def test_is_sops_encrypted_false_on_prose_mention():
    # regression: a file that only TALKS about the marker is plaintext, not encrypted.
    assert is_sops_encrypted(PROSE_MENTIONING_MARKER) is False


def test_blocks_edit_of_encrypted_file(tmp_path):
    f = tmp_path / "secrets.yml"
    f.write_text(SOPS_TEXT)
    reason = classify(str(f), REPO)
    assert reason is not None and "sops" in reason.lower(), "must block + mention sops"


def test_allows_edit_of_plaintext_yaml_that_path_pattern_would_catch(tmp_path):
    # name it like host_vars to prove the guard is content-based, not path-based
    d = tmp_path / "host_vars"
    d.mkdir()
    f = d / "daniel-server.yml"
    f.write_text(PLAINTEXT_HOST_VARS)
    assert classify(str(f), REPO) is None, "plaintext vars file must stay editable"


def test_nonexistent_file_does_not_crash():
    assert classify(os.path.join(REPO, "does/not/exist.yml"), REPO) is None


def test_blocks_the_real_secrets_file():
    # integration: the repo's actual encrypted secrets file must be blocked.
    assert classify("ansible/vars/secrets.yml", REPO) is not None


# settings.json always invokes the PRIMARY checkout's copy of the hook, so repo_root
# must come from the edited file, not from __file__ — otherwise the containers/ guard
# stays aimed at the primary checkout and a worktree edit sidesteps it entirely.


def _make_checkout(root, git_is_file):
    root.mkdir(parents=True, exist_ok=True)
    if git_is_file:
        (root / ".git").write_text("gitdir: /somewhere/.git/worktrees/x\n")
    else:
        (root / ".git").mkdir()
    return root


def test_repo_root_is_the_worktree_that_owns_the_file(tmp_path):
    primary = _make_checkout(tmp_path / "server", git_is_file=False)
    worktree = _make_checkout(primary / ".claude/worktrees/feature", git_is_file=True)
    edited = worktree / "ansible" / "roles" / "x" / "main.yml"
    edited.parent.mkdir(parents=True)
    edited.write_text("---\n")

    assert find_repo_root(str(edited), str(primary)) == str(worktree)


def test_repo_root_is_the_primary_checkout_for_a_file_outside_any_worktree(tmp_path):
    primary = _make_checkout(tmp_path / "server", git_is_file=False)
    edited = primary / "scripts" / "probe.py"
    edited.parent.mkdir(parents=True)
    edited.write_text("")

    assert find_repo_root(str(edited), "/fallback") == str(primary)


def test_repo_root_falls_back_when_no_checkout_encloses_the_file(tmp_path):
    stray = tmp_path / "nowhere" / "file.yml"
    stray.parent.mkdir(parents=True)
    stray.write_text("")

    assert find_repo_root(str(stray), "/fallback") == "/fallback"


def test_containers_guard_fires_inside_a_worktree(tmp_path):
    # the defect this derivation fixes: with repo_root pinned to the primary checkout,
    # a worktree's containers/ path did not match the guard prefix and was allowed.
    worktree = _make_checkout(tmp_path / "server/.claude/worktrees/feature", True)
    edited = worktree / "containers" / "jellyfin" / "docker-compose.yml"

    repo_root = find_repo_root(str(edited), str(tmp_path / "server"))
    assert classify(str(edited), repo_root) is not None


# ── generated documentation pages ──────────────────────────────────────────────────────


def test_blocks_edits_under_docs_reference():
    assert classify("docs/reference/services.md", REPO) is not None


def test_blocks_edits_under_docs_assets_generated():
    assert classify("docs/assets/generated/infra-map.svg", REPO) is not None


def test_allows_the_one_hand_written_page_under_docs_reference():
    """`topology.md` is prose that happens to live in the generated tree.

    Protection follows the provenance banner a generator stamps, not the path, so the only
    page there that nobody generates stays editable. A path-only guard made it uneditable
    and editing it meant reaching for a bypass — which is how a guard stops being trusted.
    """
    assert classify("docs/reference/topology.md", REPO) is None


def test_a_page_that_does_not_exist_yet_stays_guarded(tmp_path):
    """The banner check fails CLOSED.

    A path the hook cannot read cannot prove it is hand-written — a new file under
    docs/reference/, or a worktree page absent from disk. Exempting it would turn the guard
    off for exactly the case where a generated page is being created or replaced wholesale.
    """
    worktree = _make_checkout(tmp_path / "server/.claude/worktrees/feature", True)
    absent = worktree / "docs" / "reference" / "services.md"
    repo_root = find_repo_root(str(absent), str(tmp_path / "server"))
    assert classify(str(absent), repo_root) is not None


def test_the_banner_is_what_decides_not_a_hand_kept_exemption():
    """Every other page in docs/reference/ carries the banner and stays protected.

    Asserted as a CLASS over the live tree: an exemption list would have to be edited every
    time a generator is added, and the page it forgot would be silently editable.
    """
    ref = os.path.join(REPO, "docs", "reference")
    for name in sorted(os.listdir(ref)):
        if not name.endswith(".md"):
            continue
        with open(os.path.join(ref, name)) as fh:
            generated = "generated_from:" in fh.read(4096)
        verdict = classify(os.path.join(ref, name), REPO)
        assert (verdict is not None) == generated, name


def test_allows_edits_to_hand_written_docs():
    """docs/reference/ is generated; docs/ generally is not.

    A guard that blocked every runbook edit is a guard that gets switched off.
    """
    for path in (
        "docs/secret-rotation.md",
        "docs/index.md",
        "docs/networkpolicy-default-deny.md",
        "docs/archive/README.md",
    ):
        assert classify(path, REPO) is None, f"should ALLOW: {path}"


def test_allows_edits_to_the_generators_themselves():
    """The deny message tells people to edit the generator, so that path must work."""
    for path in (
        "scripts/docs/service_catalog.py",
        "scripts/infra_map/gen_infra_map.py",
    ):
        assert classify(path, REPO) is None, f"should ALLOW: {path}"


def test_blocks_an_absolute_path_into_the_generated_tree():
    """Sessions run inside .claude/worktrees/<name>, so matching must not assume a
    relative path rooted at the primary checkout."""
    assert classify(os.path.join(REPO, "docs/reference/services.md"), REPO) is not None


def test_generated_docs_guard_fires_inside_a_worktree(tmp_path):
    """Same defect the containers/ guard hit: a worktree path must still match."""
    worktree = _make_checkout(tmp_path / "server/.claude/worktrees/feature", True)
    edited = worktree / "docs" / "reference" / "services.md"

    repo_root = find_repo_root(str(edited), str(tmp_path / "server"))
    assert classify(str(edited), repo_root) is not None


def test_generated_docs_reason_names_the_generator():
    """A message that only says 'denied' sends the reader looking for the rule instead of the fix."""
    reason = classify("docs/assets/generated/infra-map.svg", REPO)
    assert "gen_infra_map.py" in reason
