- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/data"
    - "{{ role_name }}/foundrydl"

- name: Copy zip
  copy:
    src: FoundryVTT-10.288.zip
    dest: "/home/{{ SYS_USER }}/server/containers/foundry/foundrydl/FoundryVTT.zip"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
