- set_fact:
    container: "{{ item }}"

- name: Get Cloudflare Zone ID
  uri:
    url: "https://api.cloudflare.com/client/v4/zones"
    method: GET
    headers:
      X-Auth-Email: "{{ EMAIL }}"
      Authorization: "Bearer {{ CLOUDFLARE_DNS_TOKEN }}"
      Content-Type: "application/json"
  register: zone_output

- name: Get Zone ID
  set_fact:
    zone_id: "{{ zone_output | json_query(query) }}"
  vars:
    query: "json.result[?name=='{{ DOMAIN }}'].id | [0]"

- name: Check for CNAME record
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records?type=CNAME&name={{ container }}.{{ DOMAIN }}"
    method: GET
    headers:
      Authorization: "Bearer {{ CLOUDFLARE_DNS_TOKEN }}"
      Content-Type: "application/json"
  register: cname_output

- name: Check if record was found
  set_fact:
    record_count: "{{ cname_output.json.result_info.count }}"

- name: Create CNAME record if not found
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records"
    method: POST
    body: "{\"type\":\"CNAME\",\"name\":\"{{ container }}\",\"content\":\"{{ DOMAIN }}\",\"ttl\":1,\"proxied\":true}"
    body_format: json
    headers:
      Authorization: "Bearer {{ CLOUDFLARE_DNS_TOKEN }}"
      Content-Type: "application/json"
  when: record_count == "0"
