---
- name: Copy .gitconfig to home directory
  ansible.builtin.copy:
    src: .gitconfig
    dest: "{{ ansible_facts.env.HOME }}/.gitconfig"
    mode: "0644"
    backup: true
  tags: git

- name: Copy .bashrc to home directory
  ansible.builtin.copy:
    src: .bashrc
    dest: "{{ ansible_facts.env.HOME }}/.bashrc"
    mode: "0644"
    backup: true
  tags: bash

- name: Display completion message
  ansible.builtin.debug:
    msg: "Configuration files have been deployed successfully"
