- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/data"

- name: Create acme.json
  file:
    path: "/home/{{ SYS_USER }}/server/traefik/data/acme.json"
    state: touch
    mode: 0600

- name: Create config.yml from template
  template:
    src: config.yml.j2
    dest: "/home/{{ SYS_USER }}/server/traefik/data/config.yml"

- name: Create traefik.yml from template
  template:
    src: traefik.yml.j2
    dest: "/home/{{ SYS_USER }}/server/traefik/data/traefik.yml"

- name: Hash password
  shell: "echo $(htpasswd -nb {{ TRAEFIK_USER }} {{ TRAEFIK_PASSWORD }})"
  register: traefik_hash

- name: Create docker network
  shell: "docker network create {{ DOCKER_NETWORK }} || true"
  become: yes
  become_method: sudo

- include_tasks: dns.yml
  with_items:
    - "{{ role_name }}"

- include_tasks: docker.yml
  with_items:
    - "{{ role_name }}"
