- name: Creates directories
  file:
    path: "/home/{{ SYS_USER }}/server/code-server/config/.ssh"
    state: directory
    mode: 0755

- name: Check if github key exists
  stat:
    path: /templates/github
  register: github_data

- name: Copy github key
  template:
    src: github
    dest: "/home/{{ SYS_USER }}/server/code-server/config/.ssh/github"
  when: github_data.stat.exists

- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ SYS_USER }}/server/code-server/docker-compose.yml"
    
- name: Deploy Code Server
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ SYS_USER }}/server/code-server/"
  become: yes
  become_method: sudo
