- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/config/.ssh"

- name: Check if github key exists
  stat:
    path: "/home/{{ SYS_USER }}/server/ansible/roles/code-server/templates/github"
  register: github_data

- name: Copy github key
  template:
    src: github
    dest: "/home/{{ SYS_USER }}/server/code-server/config/.ssh/github"
  when: github_data.stat.exists

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
