# Generated by Django 3.2 on 2021-05-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='location',
            field=models.IntegerField(choices=[(1, 'Main'), (2, 'Archive'), (3, 'Trash')], default=1),
        ),
    ]
