---
- ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    dirs_to_create:
      - "{{ container_item.name }}/config"

- name: Create configuration.yaml from template
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "/home/{{ SYS_USER }}/server/containers/home-assistant/config/configuration.yaml"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml
