FROM n8nio/runners:latest

USER root

# Install JS packages
RUN cd /opt/runners/task-runner-javascript && pnpm add fuzzball

# Install Python packages
#RUN cd /opt/runners/task-runner-python && uv pip install numpy pandas

# Copy the config file
COPY n8n-task-runners.json /etc/n8n-task-runners.json

USER runner
