domain: ENC[AES256_GCM,data:qd+MeRsiqfx022Evq41Ehxk=,iv:11rBpB6zlZeAminkAyIaMMunJQaHttjUa0+Xx2Twp3U=,tag:ojMoYAfMLWbANJ5aUzURLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYVVtUXg1eHQveHFBTEdo
            NlBSNHp6dDhDUkZ5RUczWUhodXVIOWpLR3lvCm9mV3liRUVxUUJ2bk5BRVV6WDJy
            TnV6aGJ2cXdwTTZtamQ4b3NBQ0UzMXcKLS0tIFluM0VRcEZRTUpUTGk5R0tnd2tK
            V1hOLytPRmZJZ2I2ZWVhT3pkT2h1cE0KdH44m4ogGhh0juZS4UqYEWgjsAAXzhuc
            u/sSxccryVoWkGxDWOIt/bKEjGCDtmtqRC4euzodLjPZj2A7xi6lQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1shgt54wq7y9pk4nksxcfr5s539rh2g5uqkh9t2jlx6wj4a8aq34q4cyg7k
    lastmodified: "2026-08-27T22:14:36Z"
    mac: ENC[AES256_GCM,data:mrBA9gBNiP2GoTgBUeAOdFV5/YqzShedJ7Gwb3MD8RGPQAsU6sT9sRrNBYoPmrxr+Kv2iV8YMOOWOnNHjjijN86J5ymcNiIUiy/gu2EM0aoTeYvfZEDXNmc7A3D5nzuqwwExA9Ew2Z165JXu8v93MkVBLwZJFPFyhcLE1Y6Odn0=,iv:bcBlug9mjwkNNstV66gCEjqgBTi7Oa+SE3O7Rs3lIk8=,tag:1YkuaXerAeFMAkIQIgwTzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
