---
- name: Create required directories
  ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    common_dirs_to_create:
      - "{{ container_item.name }}/config"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Create Dockerfile from template
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "/home/{{ SYS_USER }}/server/containers/{{ role_name }}/Dockerfile"

- name: Build Docker compose
  ansible.builtin.command: docker compose build
  args:
    chdir: "/home/{{ SYS_USER }}/server/containers/{{ role_name }}/"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml
