- name: Creates directories
  file:
    path: "/home/{{ SYS_USER }}/server/pihole/data"
    state: directory
    mode: 0755

- name: Creates directories
  file:
    path: "/home/{{ SYS_USER }}/server/unbound/"
    state: directory
    mode: 0755

- name: Create docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ SYS_USER }}/server/pihole/docker-compose.yml"

- name: Pull Pihole Image
  shell: docker pull pihole/pihole:latest
  become: yes
  become_method: sudo

- name: Stop systemd-resolved.service
  shell: systemctl stop systemd-resolved.service
  become: yes
  become_method: sudo

- name: Disable systemd-resolved.service
  shell: systemctl disable systemd-resolved.service
  become: yes
  become_method: sudo

- name: Deploy Pihole
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ SYS_USER }}/server/pihole/"
  become: yes
  become_method: sudo

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertbefore: BOF
    line: '127.0.0.1 {{ SYS_USER }}'
  become: yes
  become_method: sudo

- name: Add Unbound to /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    regexp: '127.0.0.53'
    line: nameserver 172.18.0.26
  become: yes
  become_method: sudo

- name: Add Cloudflare to /etc/resolv.conf
 lineinfile:
   path: /etc/resolv.conf
   insertafter: 'nameserver 127.0.0.53'
   line: 'nameserver 1.1.1.1'
 become: yes
 become_method: sudo
