- name: Creates directories
  file:
    path: "/home/{{ SYS_USER }}/server/pihole/data"
    state: directory
    mode: 0755

- name: Creates directories
  file:
    path: "/home/{{ SYS_USER }}/server/unbound/"
    state: directory
    mode: 0755

- name: Create docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ SYS_USER }}/server/pihole/docker-compose.yml"

- name: Pull Pihole Image
  shell: docker pull pihole/pihole:latest
  become: yes
  become_method: sudo

- name: Stop systemd-resolved.service
  shell: systemctl stop systemd-resolved.service
  become: yes
  become_method: sudo

- name: Disable systemd-resolved.service
  shell: systemctl disable systemd-resolved.service
  become: yes
  become_method: sudo

- name: Deploy Pihole
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ SYS_USER }}/server/pihole/"
  become: yes
  become_method: sudo

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertbefore: BOF
    line: '127.0.0.1 {{ SYS_USER }}'
  become: yes
  become_method: sudo

- name: Remove /etc/resolv.conf symlink # TODO Add check for if already done
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create /etc/resolv.conf from template
  template:
    src: resolv.conf.j2
    dest: "/etc/resolv.conf"
