---
- ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    dirs_to_create:
      - "{{ container_item.name }}/config"
      - "data/media/tv"

- name: Create cleaner from template
  ansible.builtin.template:
    src: sonarr-episode-trimmer.py.j2
    dest: "/home/{{ SYS_USER }}/server/containers/sonarr/config/sonarr-episode-trimmer.py"
    mode: "0755"

- name: Create cleaner config from template
  ansible.builtin.template:
    src: sonarr-episode-trimmer-config.j2
    dest: "/home/{{ SYS_USER }}/server/containers/sonarr/config/sonarr-episode-trimmer-config"
    mode: "0755"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml
