---
- name: Add packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: Add GPG Key
  ansible.builtin.shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
- name: Add packages to manager
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt-get repo and cache
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    force_apt_get: true
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Install Docker Compose
  ansible.builtin.command: "curl -L --fail https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh -o /usr/local/bin/docker-compose"
  become: true

- name: Chmod Docker Compose
  ansible.builtin.file:
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: true

- name: Add sudo to user
  ansible.builtin.command: "usermod -aG docker {{ ansible_env.USER }}"
  become: true

- name: Create Network
  ansible.builtin.shell: "docker network create {{ DOCKER_NETWORK }} --subnet=172.18.0.0/16 || true"
  become: true
