- name: Creates directories
  file:
    path: "/home/{{ env.SYS_USER }}/server/portainer/data"
    state: directory
    mode: 0755

- name: Add apache2-utils
  apt:
    name: apache2-utils
    state: present
  become: yes
  become_method: sudo
  
- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ env.SYS_USER }}/server/portainer/docker-compose.yml"
    
- name: Deploy Portainer
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ env.SYS_USER }}/server/portainer/"
  become: yes
  become_method: sudo
