- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/data"

- name: Add apache2-utils
  apt:
    name: apache2-utils
    state: present
  become: yes
  become_method: sudo
  
- include_tasks: dns.yml
  with_items:
    - "{{ role_name }}"

- include_tasks: docker.yml
  with_items:
    - "{{ role_name }}"
