- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/config"

- name: Create acquis.yaml from template
  template:
    src: acquis.yaml.j2
    dest: "/home/{{ SYS_USER }}/server/crowdsec/config/acquis.yaml"

- name: Create Dockerfile from template
  template:
    src: Dockerfile.j2
    dest: "/home/{{ SYS_USER }}/server/crowdsec/Dockerfile"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"

# Pause for 5 seconds to let docker build
- pause:
    seconds: 5

- name: Add Traefik collection
  shell: docker exec crowdsec cscli collections install crowdsecurity/traefik
  become: yes
  become_method: sudo

- name: Update & Upgrade hubs
  shell: docker exec crowdsec cscli hub update && docker exec crowdsec cscli hub upgrade
  become: yes
  become_method: sudo

- name: Make sure script has correct permissions
  shell: chmod +x crowdsecUpdate.sh
  args:
    chdir: "/home/{{ SYS_USER }}/server/ansible/roles/crowdsec/scripts/"
  become: yes
  become_method: sudo

- name: Add update & upgrade cronjob
  shell: ./crowdsecUpdate.sh
  args:
    chdir: "/home/{{ SYS_USER }}/server/ansible/roles/crowdsec/scripts/"
