- name: Git Pull
  shell: git pull --all
  register: git

- name: Set Vars(Facts)
  set_fact: 
    playbook_debug: "[]"

- name: Get containers from playbook.yml
  set_fact: 
    playbook_debug: "{{ playbook_debug }} + ['item']"
  with_lines: cat "playbook.yml"
  when: '"- role:" in item'
    
- debug:
  msg: "{{ playbook_debug }}"

- name: Set Vars(Facts)
  set_fact: 
    playbook_command: ''
    playbook_roles:
      - 'docker'
      - 'traefik'
      - 'portainer'
      - 'authelia'
      - 'cloudflare-ddns'
      - 'crowdsec'
      - 'code-server'
      - 'freshrss'
      - 'librespeed'
      - 'heimdall'
      - 'uptime-kuma'
      - 'pihole'
      - 'smokeping'
      - 'filebrowser'
      - 'scrutiny'
      - 'guacamole'
      - 'nordlynx'
      - 'qbittorrent'
      - 'prowlarr'
      - 'sonarr'
      - 'radarr'
      - 'jellyfin'
      - 'minecraft'
      - 'prometheus'
      - 'grafana'
      - 'netdata'
      - 'home-assistant'
      - 'watchtower'

- name: Search git output for container names
  set_fact:
    playbook_command: "{{ playbook_command + item }}"
  loop: "{{ playbook_roles }}"
  when: item in git.stdout

- name: Setup Playbook Command
  set_fact:
    playbook_command: "{{ 'ansible-playbook playbook.yml --tags \"' + playbook_command + '\"'}}"
  when: playbook_command != ''
 
- name: Deploy updated containers, if any
  shell: "{{ playbook_command }}"
  when: playbook_command != ''
  become: yes
  become_method: sudo
