- name: Git Pull
  shell: git pull --all
  register: git

- name: Set Facts
  set_fact:
    container_names: []
    container_lines: []
    git_changed_containers_string: ''

- name: Get container lines from deploy.yml
  set_fact: 
    container_lines: "{{ container_lines + [item] }}"
  with_lines: cat "deploy.yml"
  when: '"- role:" in item'

- name: Get container name from line
  set_fact:
    container_names: "{{ container_names + [item.split(' ')[-1]] }}"
  loop: "{{ container_lines }}"

- debug:
    var: git.stdout

- name: Search git output for container names
  set_fact:
    git_changed_containers_string: "{{ git_changed_containers_string + item + ',' }}"
  loop: "{{ container_names }}"
  when: item + '/' in git.stdout

- name: Remove hanging comma
  set_fact:
    git_changed_containers_string: "{{ git_changed_containers_string[:-1] }}"

- debug:
    msg: "{{ git_changed_containers_string }}"

- name: Setup playbook command
  set_fact:
    playbook_command: "{{ 'ansible-playbook deploy.yml --tags \"' + git_changed_containers_string + '\"'}}"
 
- debug:
    msg: "{{ playbook_command }}"

- name: Deploy updated containers, if any
  shell: "{{ playbook_command }}"
  when: git_changed_containers_string != ''
  become: yes
  become_method: sudo
