- name: Git Pull
  shell: git pull --all
  register: git

- name: Set Ansible command
  set_fact: 
    playbook_command: ''
    playbook_roles:
      - 'docker'
      - 'traefik'
      - 'portainer'
      - 'authelia'
      - 'cloudflare-ddns'
      - 'crowdsec'
      - 'code-server'
      - 'freshrss'
      - 'librespeed'
      - 'heimdall'
      - 'uptime-kuma'
      - 'pihole'
      - 'smokeping'
      - 'filebrowser'
      - 'scrutiny'
      - 'guacamole'
      - 'nordlynx'
      - 'qbittorrent'
      - 'prowlarr'
      - 'sonarr'
      - 'radarr'
      - 'jellyfin'
      - 'minecraft'
      - 'prometheus'
      - 'grafana'
      - 'netdata'
      - 'home-assistant'
      - 'watchtower'
      - 'git'

- name: Loop over stdout_lines
  set_fact:
    playbook_command: "{{ playbook_command + item }}"
  loop: "{{ playbook_roles }}"
  when: item in git.stdout

- name: Setup Command
  set_fact:
    playbook_command: "{{ 'ansible-playbook playbook.yml --tags' + playbook_command }}"

- debug:
    msg: "{{ playbook_command }}"

- name: Deploy updated containers
  shell: pwd
  register: test

- debug:
    msg: "{{ test.stdout }}"
