---
- name: Deploy Containers
  hosts: homeservers
  gather_facts: false
  vars_files:
    - .env
  pre_tasks:
    - name:  Only run on the machine executing this command
      meta: end_host
      when: inventory_hostname != lookup('pipe', 'hostname')

    - name: Now safe to gather facts
      setup: # Gather facts now that we know we are on the right host
  tasks:
    - name: Run roles respecting tags
      include_role:
        name: "{{ container_item.name }}"
      loop: "{{ containers_list }}"
      loop_control:
        loop_var: container_item
      when:
        - "'all' in ansible_run_tags or (container_item.tags | intersect(ansible_run_tags) | length > 0)"
      tags: always
