---
- name: Setup Server
  hosts: localhost
  gather_facts: no
  vars_files:
    - .env
  roles:
    - { role: crowdsec,           tags: [ 'crowdsec' ]}
    - { role: traefik,            tags: [ 'traefik' ]}
    - { role: portainer,          tags: [ 'portainer' ]}
    - { role: authelia,           tags: [ 'authelia' ]}
    - { role: autoheal,           tags: [ 'autoheal' ]}
    - { role: cloudflare-ddns,    tags: [ 'cloudflare-ddns' ]}
    - { role: code-server,        tags: [ 'code-server' ]}
    - { role: change-detection,   tags: [ 'change-detection' ]}
    - { role: hoppscotch,         tags: [ 'hoppscotch' ]}
    - { role: freshrss,           tags: [ 'freshrss' ]}
    - { role: heimdall,           tags: [ 'heimdall' ]}
    - { role: uptime-kuma,        tags: [ 'uptime-kuma' ]}
    - { role: file-browser,       tags: [ 'file-browser' ]}
    - { role: qbittorrent,        tags: [ 'qbittorrent', 'media' ]}
    - { role: prowlarr,           tags: [ 'prowlarr', 'media' ]}
    - { role: sonarr,             tags: [ 'sonarr', 'media' ]}
    - { role: radarr,             tags: [ 'radarr', 'media' ]}
    - { role: bazarr,             tags: [ 'bazarr', 'media' ]}
    - { role: jellyfin,           tags: [ 'jellyfin', 'media' ]}
    - { role: prometheus,         tags: [ 'prometheus', 'monitoring' ]}
    - { role: grafana,            tags: [ 'grafana', 'monitoring' ]}
    - { role: netdata,            tags: [ 'netdata', 'monitoring' ]}
    - { role: minecraft,          tags: [ 'minecraft' ]}
    - { role: cloudflare-ddns-mc, tags: [ 'cloudflare-ddns-mc' ]}
    - { role: home-assistant,     tags: [ 'home-assistant' ]}
    - { role: watchtower,         tags: [ 'watchtower' ]}
    - { role: healthchecks,       tags: [ 'healthchecks' ]}
    - { role: foundry,            tags: [ 'foundry' ]}
    - { role: whoogle,            tags: [ 'whoogle' ]}
    - { role: ghost,              tags: [ 'ghost' ]}
    - { role: littlelink,         tags: [ 'littlelink' ]}
    - { role: emulatorjs,         tags: [ 'emulatorjs' ]}
    - { role: scrutiny,           tags: [ 'scrutiny' ]}
    - { role: duplicati,          tags: [ 'duplicati' ]}
    - { role: pihole,             tags: [ 'pihole' ]}
