---
- name: Initial Server Setup
  hosts: homeservers
  become: true
  gather_facts: false
  env_file: .env
  pre_tasks:
    - name:  Only run on the machine executing this command
      meta: end_host
      when: inventory_hostname != lookup('pipe', 'hostname')

    - name: Gather facts
      setup: # Gather facts now that we know we are on the right host
  roles:
    - { role: config_files,             tags: [ 'config_files' ]}
    - { role: initial_setup,            tags: [ 'initial_setup' ]}
    - { role: docker_install,           tags: [ 'docker_install' ]}
    - { role: optimize_pi,              tags: [ 'optimize_pi' ], when: inventory_hostname == 'daniel-pi' }
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

    - name: Restart ZRAM
      service:
        name: zramswap
        state: restarted

    - name: Restart Watchdog
      service:
        name: watchdog
        state: restarted

    - name: Restart Docker
      service:
        name: docker
        state: restarted

    - name: Reboot Pi
      reboot:
        msg: "Rebooting to apply low-level hardware changes (GPU/Watchdog/Log2Ram)"
