---
- name: Git Pull (Ensure repo is up to date)
  ansible.builtin.git:
    repo: "{{ github_repo }}"
    dest: "/home/{{ sys_user }}/server"
    version: HEAD # noqa: latest[git]
    update: true
  register: common_git

- name: Show git output
  ansible.builtin.debug:
    var: common_git.stdout_lines

- name: Find containers with changed role files
  ansible.builtin.set_fact:
    common_git_changed_tags: "{{ common_git_changed_tags | default([]) + [item.name] }}"
  loop: "{{ containers_list }}"
  when: ('roles/containers/' + item.name + '/') in common_git.stdout

- name: Build tag string for changed containers
  ansible.builtin.set_fact:
    common_git_changed_tag_string: "{{ common_git_changed_tags | default([]) | join(',') }}"

- name: Show planned redeploy tags
  ansible.builtin.debug:
    msg: "Containers to redeploy: {{ common_git_changed_tag_string }}"

- name: Deploy updated containers, if any
  ansible.builtin.command:
    cmd: "ansible-playbook deploy.yml --tags '{{ common_git_changed_tag_string }}'"
    chdir: "/home/{{ sys_user }}/server/ansible"
  when: common_git_changed_tag_string != ''
  changed_when: true
