---
- name: Git Pull
  ansible.builtin.command: git pull --all
  register: common_git

- name: Show git output
  ansible.builtin.debug:
    var: common_git.stdout_lines

- name: Set Facts
  ansible.builtin.set_fact:
    common_container_names: []
    common_container_lines: []
    common_git_changed_containers: ""

- name: Get container lines from deploy.yml
  ansible.builtin.set_fact:
    common_container_lines: "{{ common_container_lines + [item] }}"
  with_lines: cat "deploy.yml"
  when: '"role:" in item'

- name: Get container name from line
  ansible.builtin.set_fact:
    common_container_names: "{{ common_container_names + [item.split(' ')[7]] }}"
  loop: "{{ common_container_lines }}"

- name: Search git output for container names
  ansible.builtin.set_fact:
    common_git_changed_containers: "{{ common_git_changed_containers + item }}"
  loop: "{{ common_container_names }}"
  when: item[:-1] + '/' in common_git.stdout

- name: Remove hanging comma
  ansible.builtin.set_fact:
    common_git_changed_containers: "{{ common_git_changed_containers[:-1] }}"

- name: Setup playbook command
  ansible.builtin.set_fact:
    common_playbook_command: "{{ 'ansible-playbook deploy.yml --tags \"' + common_git_changed_containers + '\"' }}"

- name: Show playbook command
  ansible.builtin.debug:
    msg: "{{ common_playbook_command }}"

- name: Deploy updated containers, if any
  ansible.builtin.command: "{{ common_playbook_command }}"
  when: common_git_changed_containers != ''
  become: true
  become_method: ansible.builtin.sudo
