---
- name: Set common container name
  ansible.builtin.set_fact:
    common_container: "{{ item }}"

- name: Get Cloudflare Zone ID
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones"
    method: GET
    headers:
      X-Auth-Email: "{{ EMAIL }}"
      Authorization: "Bearer {{ CLOUDFLARE_DNS_TOKEN }}"
      Content-Type: "application/json"
  register: common_zone_output

- name: Get Zone ID
  ansible.builtin.set_fact:
    common_zone_id: "{{ common_zone_output | json_query(common_query) }}"
  vars:
    common_query: "json.result[?name=='{{ DOMAIN }}'].id | [0]"

- name: Check for CNAME record
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ common_zone_id }}/dns_records?type=CNAME&name={{ common_container }}.{{ DOMAIN }}"
    method: GET
    headers:
      Authorization: "Bearer {{ CLOUDFLARE_DNS_TOKEN }}"
      Content-Type: "application/json"
  register: common_cname_output

- name: Check if record was found
  ansible.builtin.set_fact:
    common_record_count: "{{ common_cname_output.json.result_info.count }}"

- name: Create CNAME record if not found
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ common_zone_id }}/dns_records"
    method: POST
    body: "{\"type\":\"CNAME\",\"name\":\"{{ common_container }}\",\"content\":\"{{ DOMAIN }}\",\"ttl\":1,\"proxied\":true}"
    body_format: json
    headers:
      Authorization: "Bearer {{ CLOUDFLARE_DNS_TOKEN }}"
      Content-Type: "application/json"
  when: common_record_count == "0"
