- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/config"
 
- name: Hash password
  shell: "docker run authelia/authelia:latest authelia crypto hash generate argon2 --password '{{ AUTHELIA_PASSWORD }}'"
  register: authelia_hash_output
  become: yes
  become_method: sudo

- name: Remove prefix from hash
  set_fact:
    authelia_password_hash: "{{ authelia_hash_output.stdout | regex_replace('^Digest: ', '') }}"

- name: Debug the cleaned hash
  debug:
    msg: "{{ authelia_password_hash }}"
 
- name: Create configuration.yml from template
  template:
    src: configuration.yml.j2
    dest: "/home/{{ SYS_USER }}/server/authelia/config/configuration.yml"
    
- name: Create users_database.yml from template
  template:
    src: users_database.yml.j2
    dest: "/home/{{ SYS_USER }}/server/authelia/config/users_database.yml"

# - include_tasks: dns.yml
#   with_items:
#     - auth

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
