#!/usr/bin/env python3
"""Emit an /etc/hosts block for every homelab `.local` name, with the right IP per service.

Why this exists: Mullvad's DNS-leak protection rejects :53 to any resolver but its own, so a
client with Mullvad connected cannot query Pi-hole at all — LAN HTTP works while LAN DNS
returns "connection refused" (see docs/wireguard-private-homelab-access.md A6). A hosts entry
emits no DNS query, so it sidesteps the reject entirely and is the only option that keeps
Mullvad's posture intact. It also survives the fact that DHCP hands out the ISP's resolvers
rather than Pi-hole, which otherwise resolves every `.local` name to daniel-server via the
public wildcard — wrong for anything on the k3s VIP.

The cost of a hosts file is that it has no wildcard, so every name must be listed. That is
what this script removes: the list is derived from the same inventory Pi-hole's dnsmasq
config is generated from, so it cannot drift as services migrate between hosts.

Deliberately parses the inventory YAML directly instead of going through Ansible. Those files
reference SOPS-encrypted values (`{{ authelia_jwt_secret }}` and friends),
and templating the whole structure would demand secrets this script has no business holding.
Only `name`, `port`, `hostname` and `platform` are ever read.

Usage:
    uv run python scripts/dev/gen_hosts_block.py           # print the block
    uv run python scripts/dev/gen_hosts_block.py --sudo    # print, plus install instructions
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

import yaml

# Reach the sibling package directories: a directly-invoked script gets only its own
# directory on sys.path, and pyproject's `pythonpath` is a pytest setting.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.repo_paths import INVENTORY, REPO  # noqa: E402

BEGIN = (
    "# BEGIN homelab — generated by scripts/dev/gen_hosts_block.py, do not hand-edit"
)
END = "# END homelab"

# Hosts whose containers_list carries `.local.<domain>` names, and where the address for a
# service on that host comes from. daniel-pi is deliberately absent: its services are reached
# at daniel-pi.lan:<port> over plain HTTP, not through Traefik on a `.local` name (a `.local`
# subdomain would inherit Traefik's HSTS and force-upgrade them to HTTPS). It contributes only
# the host-record below.
LOCAL_NAME_HOSTS = ("daniel-server", "daniel-box")

_JINJA = re.compile(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}")


def read_domain() -> str:
    """Read `domain` out of the SOPS store, the only value here that is encrypted.

    Extracts the single key rather than decrypting the file, so nothing else is ever in
    memory. Callers without the age key pass --domain instead, which is also what keeps the
    tests (and CI) free of any decrypt step.
    """
    proc = subprocess.run(
        [
            "sops",
            "-d",
            "--extract",
            '["domain"]',
            str(REPO / "ansible" / "vars" / "secrets.yml"),
        ],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(
            f"could not read `domain` from SOPS (exit {proc.returncode}). "
            f"Pass --domain <domain> if this host has no age key.\n{proc.stderr.strip()}"
        )
    return proc.stdout.strip()


def load_vars(domain: str | None = None) -> dict:
    """Collect the handful of scalars needed to resolve hostnames and pick addresses."""
    all_vars = yaml.safe_load((INVENTORY / "group_vars" / "all.yml").read_text()) or {}
    out = {
        "domain": domain or read_domain(),
        "k3s_metallb_ingress_vip": all_vars["k3s_metallb_ingress_vip"],
    }
    for host in (*LOCAL_NAME_HOSTS, "daniel-pi"):
        hv = yaml.safe_load((INVENTORY / "host_vars" / f"{host}.yml").read_text()) or {}
        out[f"{host}:server_ip"] = hv["server_ip"]
        out[f"{host}:containers_list"] = hv.get("containers_list", []) or []
    return out


def resolve(value: str, scalars: dict) -> str:
    """Substitute `{{ var }}` against the scalar map, erroring on anything unresolved.

    Failing loudly matters: a silently unresolved `{{ some_var }}` in a hostname would emit a
    hosts entry for a hostname that does not exist, and the symptom (one service unreachable)
    looks nothing like its cause.
    """
    resolved = _JINJA.sub(lambda m: str(scalars.get(m.group(1), m.group(0))), value)
    leftover = _JINJA.search(resolved)
    if leftover:
        raise KeyError(
            f"unresolved variable {leftover.group(0)!r} in hostname {value!r}"
        )
    return resolved


def entries(scalars: dict) -> list[tuple[str, str]]:
    """Build (ip, fqdn) pairs for every web-facing service, plus the Pi's host-record."""
    domain = scalars["domain"]
    vip = scalars["k3s_metallb_ingress_vip"]
    out: list[tuple[str, str]] = []

    for host in LOCAL_NAME_HOSTS:
        host_ip = scalars[f"{host}:server_ip"]
        for svc in scalars[f"{host}:containers_list"]:
            # `port` is the inventory's marker for "web-facing" (see the repo CLAUDE.md), and
            # so for "has a Traefik route and therefore a name". Erring generous is right
            # here: a spurious entry just maps a name to the host already serving it, whereas
            # a missing one is the exact failure this script exists to prevent.
            if not svc.get("port"):
                continue
            # k3s entries without a hostname (traefik itself) have no route of their own —
            # same skip the dnsmasq template makes.
            is_k8s = svc.get("platform", "docker") == "k8s"
            if is_k8s and "hostname" not in svc:
                continue
            name = resolve(str(svc.get("hostname", svc["name"])), scalars)
            out.append((vip if is_k8s else host_ip, f"{name}.local.{domain}"))

    out.extend(hand_written_routes(scalars))
    out.append((scalars["daniel-pi:server_ip"], "daniel-pi.lan"))
    return sorted(set(out))


def hand_written_routes(scalars: dict) -> list[tuple[str, str]]:
    """Scrape `.local` router rules written literally into Docker compose templates.

    Not every service gets its route from the shared `labels()` macro, and the ones that
    don't are invisible to a containers_list scan (e.g. livesync/n8n's hand-rolled routers,
    left in their Docker roles as build/reference source after their k8s migration).
    Authelia was the important historical case — it had no `port` and hand-rolled
    `auth.local.<domain>`, the login-redirect target every protected service bounced
    through — but it moved to k8s at E7 (2026-08-13) with a real `port`, so the main
    containers_list loop above finds it now; this scrape no longer needs to.

    k8s roles need no equivalent scrape: their routes all come from the ingressroute macro,
    which is driven by the same `hostname` key the loop above reads.
    """
    domain = scalars["domain"]
    ip = scalars["daniel-server:server_ip"]
    pattern = re.compile(r"Host\(`([a-z0-9-]+)\.local\.\{\{ ?domain ?\}\}`\)")
    names = set()
    for template in (REPO / "ansible" / "roles" / "containers").glob(
        "*/templates/*.j2"
    ):
        names.update(pattern.findall(template.read_text()))
    return [(ip, f"{name}.local.{domain}") for name in names]


def render(pairs: list[tuple[str, str]]) -> str:
    width = max(len(ip) for ip, _ in pairs)
    body = "\n".join(
        f"{ip:<{width}}  {fqdn}"
        for ip, fqdn in sorted(pairs, key=lambda p: (p[0], p[1]))
    )
    return f"{BEGIN}\n{body}\n{END}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--sudo", action="store_true", help="also print install instructions"
    )
    ap.add_argument(
        "--domain", help="skip the SOPS read (for hosts without the age key)"
    )
    args = ap.parse_args()

    scalars = load_vars(args.domain)
    pairs = entries(scalars)
    block = render(pairs)
    print(block)

    if args.sudo:
        # Anchor the sed range on the ASCII prefix of each marker, not the whole line: the
        # markers contain both a `/` (which would close sed's address delimiter) and an
        # em-dash, and escaping either into a working one-liner is more trouble than it is
        # worth when "# BEGIN homelab" is already unique in a hosts file.
        print(
            f"\n# {len(pairs)} names. Re-running is safe — delete the old block first:\n"
            f"#   sudo sed -i '/# BEGIN homelab/,/# END homelab/d' /etc/hosts\n"
            f"#   uv run python scripts/dev/gen_hosts_block.py | sudo tee -a /etc/hosts",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
