- name: Creates directories
  file:
    path: "/home/{{ SYS_USER }}/server/scrutiny/config"
    state: directory
    mode: 0755
  
- name: Create docker-compose from template
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ SYS_USER }}/server/scrutiny/docker-compose.yml"
    
- name: Deploy Scrutiny
  shell: docker-compose up -d --force-recreate
  args:
    chdir: "/home/{{ SYS_USER }}/server/scrutiny/"
  become: yes
  become_method: sudo

# Pause for 5 seconds to let docker build
- pause:
    seconds: 5

- name: Run metrics collector
  shell: docker exec scrutiny scrutiny-collector-metrics run
  become: yes
  become_method: sudo
