---
- ansible.builtin.include_role:
    name: common
    tasks_from: setup_dirs.yml
  vars:
    dirs_to_create:
      - "{{ container_item.name }}/configs"
      - "{{ container_item.name }}/trainingData"

- name: Copy trainingdata
  ansible.builtin.copy:
    src: eng.traineddata
    dest: "/home/{{ SYS_USER }}/server/containers/{{ role_name }}/trainingData/eng.traineddata"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- name: Deploy Container
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_deploy.yml
