- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/configs/"
    - "{{ role_name }}/trainingData/"

- name: Copy trainingdata
  copy:
    src: eng.traineddata
    dest: "/home/{{ SYS_USER }}/server/containers/{{ role_name }}/trainingData/eng.traineddata"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
