- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/config/wg_confs"
    - "data/torrents"

- name: Copy wg0.conf
  copy:
    src: wg0.conf.j2
    dest: "/home/{{ SYS_USER }}/server/{{ role_name }}/config/wg_confs/wg0.conf"

- name: Extract transcode.zip into /var/lib/foo
  unarchive:
    src: transcode.zip
    dest: "/home/{{ SYS_USER }}/server/qbittorrent/"

# - include_tasks: dns.yml
#   with_items:
#     - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
