- include_tasks: directory.yml
  with_items:
    - "{{ role_name }}/config"
    - "media/downloads"

- include_tasks: dns.yml
  with_items:
    - "{{ role_name }}"

- include_tasks: docker.yml
  vars:
    container: "{{ role_name }}"
