
- name: Update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install required packages
  apt:
    name:
      - linux-raspi
      - openvswitch-switch-dpdk
    state: present
  become: true
  when: inventory_hostname == 'daniel-pi'

- name: Pip Install
  pip:
    name:
      - ansible-lint

- name: Install required packages
  apt:
    name:
      - unzip
      - unattended-upgrades
      - update-notifier-common
    state: present
  become: true

- name: Set SSH directory permissions
  file:
    path: ~/.ssh
    mode: '0700'
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: Configure SSH security settings
  lineinfile:
    path: "{{ ssh_config_path }}"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
  loop:
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "PermitEmptyPasswords", value: "no" }
    - { key: "PermitRootLogin", value: "no" }
    - { key: "IgnoreRhosts", value: "yes" }
    - { key: "ChallengeResponseAuthentication", value: "no" }
  notify: Restart SSH

- name: Schedule sudo crontab for weekly restart
  cron:
    name: "Weekly system restart"
    minute: "30"
    hour: "7"
    weekday: "0"
    job: "/sbin/shutdown -r +5"
    user: root
  become: true

- name: Schedule Docker image cleanup
  cron:
    name: "Clean unused Docker images"
    minute: "30"
    hour: "6"
    job: "/usr/bin/docker image prune -a -f"
    user: "{{ ansible_user_id }}"
  become: true

- name: Schedule Docker Compose image pull
  cron:
    name: "Repull docker-compose"
    minute: "35"
    hour: "6"
    job: "/usr/bin/docker image pull ghcr.io/linuxserver/docker-compose:latest"
    user: "{{ ansible_user_id }}"
  become: true

- name: Create cron job to clear ansible.log weekly
  cron:
    name: "Clear ansible log file"
    minute: "0"
    hour: "6"
    weekday: "0" # 0 is Sunday
    job: "truncate -s 0 /home/ubuntu/server/ansible/ansible.log"
  become: true

- name: Configure UFW firewall
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Enable UFW firewall
  ufw:
    state: enabled
